"""Shared banner/comment formatting helpers."""

from __future__ import annotations
import os
import datetime

from ..graph import OnnxGraph
from ..nodes import OP_NAMES, MatmulNode, ConvNode, PoolNode, ReshapeNode, SpaceToDepthNode


def _banner(title: str) -> str:
    bar = "/" * 72
    return f"\n{bar}\n/* {title:<68} */\n{bar}\n"


def _file_banner(filename: str, graph: OnnxGraph, model_path: str) -> str:
    ts         = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    model_name = os.path.basename(model_path)
    n_nodes    = len(graph.nodes)

    # Collect op names per node type
    ops_used = sorted({
        "MatMul"   if isinstance(sn, MatmulNode)
        else "Conv"    if isinstance(sn, ConvNode)
        else "Reshape" if isinstance(sn, ReshapeNode)
        else sn.onnx_node.op_type if isinstance(sn, (PoolNode, SpaceToDepthNode))
        else OP_NAMES[sn.op_code]
        for sn in graph.nodes
    })
    ops_str = ", ".join(ops_used) if ops_used else "(none)"

    # Identify which kernel(s) are used
    has_matmul   = any(isinstance(sn, MatmulNode)  for sn in graph.nodes)
    has_conv     = any(isinstance(sn, ConvNode)    for sn in graph.nodes)
    has_pool     = any(isinstance(sn, PoolNode)    for sn in graph.nodes)
    has_vectorop = any(
        not isinstance(sn, (MatmulNode, ConvNode, PoolNode, ReshapeNode, SpaceToDepthNode))
        for sn in graph.nodes
    )
    kernel_parts = []
    if has_vectorop:
        kernel_parts.append("VectorOPKernel (element-wise, 1-D, II=1)")
    if has_matmul:
        kernel_parts.append("MatmulKernel (matrix multiply, tiled)")
    if has_conv:
        kernel_parts.append("ConvKernel (2-D convolution, NCHW)")
    if has_pool:
        kernel_parts.append("PoolingKernel (2-D pooling, NCHW)")
    kernel_line = " + ".join(kernel_parts) if kernel_parts else "unknown"

    lines = [
        "/*",
        f" * {filename}",
        " * Auto-generated by inference-scheduler",
        f" * Source model : {model_name}",
        f" * Generated at : {ts}",
        f" * Scheduled ops: {n_nodes}",
        f" * Op codes used: {ops_str}",
        " *",
    ]
    for t in graph.input_tensors:
        lines.append(f" * Input  : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    for t in graph.output_tensors:
        lines.append(f" * Output : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    lines += [
        " *",
        " * Target: Xilinx KV260 bare-metal, ap_fixed<16,8> data type",
        f" * Kernel: {kernel_line}",
        " */",
    ]
    return "\n".join(lines)
