"""Mixin that generates CMakeLists.txt."""

from __future__ import annotations
import os



class _CmakeMixin:
    """Generates CMakeLists.txt."""

    def generate_cmake(self) -> str:
        """Content for CMakeLists.txt."""
        inputs  = self._graph.input_tensors
        outputs = self._graph.output_tensors
        in_desc  = ", ".join(f"{t.onnx_name}{t.shape}" for t in inputs)
        out_desc = ", ".join(f"{t.onnx_name}{t.shape}" for t in outputs)
        model_basename = os.path.basename(self._model_path)
        active = self._active_kernels
        kernel_names_str = " + ".join(kd.name for kd in active)

        # Generate per-kernel driver verification blocks
        drv_verify_blocks = []
        for kd in active:
            common_files = "\n".join(
                f"        driver/{f}"
                for f in kd.driver_files
                if not (f.endswith("_sinit.c") or f.endswith("_linux.c"))
            )
            drv_verify_blocks.append(
                f"# {kd.name} — AXI base 0x{kd.axi_base:08X}, UIO: {kd.uio_default}\n"
                f"foreach(_drv\n"
                f"{common_files})\n"
                f"    if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_drv}}\")\n"
                f"        message(FATAL_ERROR\n"
                f"            \"Driver file not found: ${{_drv}}\\n\"\n"
                f"            \"Populate driver/ — see driver/README.md\")\n"
                f"    endif()\n"
                f"endforeach()\n"
            )
        drv_verify_str = "\n".join(drv_verify_blocks)

        # Target-specific driver files (sinit.c / linux.c) per kernel
        sinit_files = "\n".join(
            f"    driver/{kd.driver_prefix}_sinit.c" for kd in active
        )
        linux_files = "\n".join(
            f"    driver/{kd.driver_prefix}_linux.c" for kd in active
        )

        # Common (shared) kernel driver .c sources for the static library
        common_drv_sources = "\n".join(
            f"    driver/{kd.driver_prefix}.c" for kd in active
        )

        # Per-kernel UIO instance override macros for test
        instance_overrides = "\n".join(
            f"    if(DEFINED {kd.instance_macro})\n"
            f"        target_compile_definitions(test_inference PRIVATE\n"
            f"            {kd.instance_macro}=${{{kd.instance_macro}}})\n"
            f"    endif()"
            for kd in active
        )

        return (
            f"# CMakeLists.txt — auto-generated by inference-scheduler\n"
            f"# Model  : {model_basename}\n"
            f"# Input  : {in_desc}\n"
            f"# Output : {out_desc}\n"
            f"# Kernels: {kernel_names_str}\n"
            f"#\n"
            f"# Builds a static library 'inference' from src/inference.c and the\n"
            f"# hardware kernel driver sources in driver/.\n"
            f"#\n"
            f"# Two targets are supported via the INFERENCE_TARGET cache variable:\n"
            f"#\n"
            f"#   BARE_METAL (default)\n"
            f"#     Cross-compile for Xilinx standalone / FreeRTOS BSP.\n"
            f"#     Requires -DBSP_INCLUDE_DIR=<path> and an aarch64-none-elf toolchain.\n"
            f"#     Drivers: *_sinit.c  (static device lookup, one per kernel)\n"
            f"#     Cache:   Xil_DCacheFlushRange / Xil_DCacheInvalidateRange\n"
            f"#\n"
            f"#   LINUX\n"
            f"#     Build natively on KV260 Linux (or cross-compile with aarch64-linux-gnu).\n"
            f"#     No BSP required; uses the UIO mmap driver and standard libc.\n"
            f"#     Drivers: *_linux.c  (open/mmap /dev/uioX, one per kernel)\n"
            f"#     Cache:   no-op (KV260 HPC ports are hardware cache-coherent)\n"
            f"#\n"
            f"# Usage — BARE_METAL:\n"
            f"#   cmake -S . -B build-bm \\\n"
            f"#     -DINFERENCE_TARGET=BARE_METAL \\\n"
            f"#     -DCMAKE_TOOLCHAIN_FILE=<toolchain-aarch64-none-elf.cmake> \\\n"
            f"#     -DBSP_INCLUDE_DIR=<bsp>/psu_cortexa53_0/include\n"
            f"#   cmake --build build-bm\n"
            f"#\n"
            f"# Usage — LINUX:\n"
            f"#   cmake -S . -B build-linux -DINFERENCE_TARGET=LINUX\n"
            f"#   cmake --build build-linux\n"
            f"\n"
            f"cmake_minimum_required(VERSION 3.19)\n"
            f"project(inference VERSION 1.0 LANGUAGES C)\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Target selection\n"
            f"# -----------------------------------------------------------------------\n"
            f"set(INFERENCE_TARGET \"BARE_METAL\" CACHE STRING\n"
            f"    \"Build target: BARE_METAL (standalone BSP) or LINUX (UIO mmap)\")\n"
            f"set_property(CACHE INFERENCE_TARGET PROPERTY STRINGS BARE_METAL LINUX)\n"
            f"\n"
            f"if(NOT INFERENCE_TARGET STREQUAL \"BARE_METAL\" AND\n"
            f"   NOT INFERENCE_TARGET STREQUAL \"LINUX\")\n"
            f"    message(FATAL_ERROR\n"
            f"        \"INFERENCE_TARGET must be BARE_METAL or LINUX, \"\n"
            f"        \"got '${{INFERENCE_TARGET}}'\")\n"
            f"endif()\n"
            f"\n"
            f"message(STATUS \"inference: building for target ${{INFERENCE_TARGET}}\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Verify driver sources (copy from HLS synthesis output or see driver/README.md)\n"
            f"# -----------------------------------------------------------------------\n"
            f"{drv_verify_str}\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Target-specific driver source + include/link settings\n"
            f"# -----------------------------------------------------------------------\n"
            f"if(INFERENCE_TARGET STREQUAL \"BARE_METAL\")\n"
            f"\n"
            f"    set(_TARGET_DRIVERS\n"
            f"{sinit_files})\n"
            f"    foreach(_drv ${{_TARGET_DRIVERS}})\n"
            f"        if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_drv}}\")\n"
            f"            message(FATAL_ERROR\n"
            f"                \"BARE_METAL: driver file not found: ${{_drv}}\")\n"
            f"        endif()\n"
            f"    endforeach()\n"
            f"\n"
            f"    if(NOT BSP_INCLUDE_DIR)\n"
            f"        message(WARNING\n"
            f"            \"BARE_METAL: BSP_INCLUDE_DIR is not set.\\n\"\n"
            f"            \"Set it to the Vitis standalone BSP include directory, e.g.:\\n\"\n"
            f"            \"  cmake -DBSP_INCLUDE_DIR=<bsp>/psu_cortexa53_0/include\")\n"
            f"    endif()\n"
            f"    set(_TARGET_INCDIRS ${{BSP_INCLUDE_DIR}})\n"
            f"\n"
            f"else() # LINUX\n"
            f"\n"
            f"    set(_TARGET_DRIVERS\n"
            f"{linux_files})\n"
            f"    foreach(_drv ${{_TARGET_DRIVERS}})\n"
            f"        if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_drv}}\")\n"
            f"            message(FATAL_ERROR\n"
            f"                \"LINUX: driver file not found: ${{_drv}}\")\n"
            f"        endif()\n"
            f"    endforeach()\n"
            f"\n"
            f"    # XRT runtime — provides xclAllocBO/xclSyncBO/xclMapBO for DMA buffers.\n"
            f"    # Locate XRT via pkg-config (preferred) or a manual XRT_DIR fallback.\n"
            f"    find_package(PkgConfig QUIET)\n"
            f"    if(PkgConfig_FOUND)\n"
            f"        pkg_check_modules(XRT QUIET xrt)\n"
            f"    endif()\n"
            f"\n"
            f"    if(XRT_FOUND)\n"
            f"        message(STATUS \"inference: XRT found via pkg-config (${{XRT_VERSION}})\")\n"
            f"        set(_TARGET_INCDIRS ${{XRT_INCLUDE_DIRS}})\n"
            f"        set(_TARGET_LIBS    ${{XRT_LIBRARIES}})\n"
            f"    else()\n"
            f"        set(XRT_DIR \"/opt/xilinx/xrt\" CACHE PATH\n"
            f"            \"XRT installation prefix, used when pkg-config cannot find xrt\")\n"
            f"        if(NOT EXISTS \"${{XRT_DIR}}/include/xrt.h\")\n"
            f"            message(WARNING\n"
            f"                \"XRT not found via pkg-config and header missing at \"\n"
            f"                \"${{XRT_DIR}}/include/xrt.h\\n\"\n"
            f"                \"Install XRT or set -DXRT_DIR=<prefix>.\")\n"
            f"        endif()\n"
            f"        set(_TARGET_INCDIRS ${{XRT_DIR}}/include)\n"
            f"        set(_TARGET_LIBS    ${{XRT_DIR}}/lib/libxrt_core.so)\n"
            f"    endif()\n"
            f"\n"
            f"endif()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Static library\n"
            f"# -----------------------------------------------------------------------\n"
            f"add_library(inference STATIC\n"
            f"    src/inference.c\n"
            f"    src/inference_buf.c\n"
            f"{common_drv_sources}\n"
            f"    ${{_TARGET_DRIVERS}}\n"
            f")\n"
            f"\n"
            f"target_include_directories(inference\n"
            f"    PUBLIC  ${{CMAKE_CURRENT_SOURCE_DIR}}/include\n"
            f"    PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}}/driver\n"
            f"    PRIVATE ${{_TARGET_INCDIRS}}\n"
            f")\n"
            f"\n"
            f"target_compile_options(inference PRIVATE -Wall -Wextra -O2)\n"
            f"{self._cmake_host_ops()}"
            f"\n"
            f"if(DEFINED _TARGET_LIBS)\n"
            f"    target_link_libraries(inference PUBLIC ${{_TARGET_LIBS}})\n"
            f"endif()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# External weight files (.dat) — loaded at runtime by inference_init()\n"
            f"# -----------------------------------------------------------------------\n"
            f"set(INFERENCE_WEIGHTS_DIR \"${{CMAKE_CURRENT_SOURCE_DIR}}\"\n"
            f"    CACHE PATH \"Runtime directory that contains the weights/ subdirectory\")\n"
            f"target_compile_definitions(inference PRIVATE\n"
            f"    INFERENCE_WEIGHTS_DIR=\"${{INFERENCE_WEIGHTS_DIR}}\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Install\n"
            f"# -----------------------------------------------------------------------\n"
            f"install(TARGETS inference ARCHIVE DESTINATION lib)\n"
            f"install(FILES include/inference.h DESTINATION include)\n"
            f"install(DIRECTORY weights/ DESTINATION weights\n"
            f"    FILES_MATCHING PATTERN \"*.dat\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Per-layer profiling (off by default — adds ~2 clock_gettime calls\n"
            f"# per node, plus a few hundred bytes of static counters)\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Enable: cmake -DINFERENCE_PROFILING=ON ...\n"
            f"# Anything that links the 'inference' target (e.g. bench_mnist) will\n"
            f"# inherit -DINFERENCE_PROFILING=1 via the PUBLIC compile definition.\n"
            f"option(INFERENCE_PROFILING\n"
            f"       \"Compile in per-layer wall-clock profiling (inference_prof.c)\""
            f" OFF)\n"
            f"if(INFERENCE_PROFILING)\n"
            f"    # Dispatcher + every DDR backend under src/ddr/.  Each backend\n"
            f"    # auto-registers; the dispatcher picks the first one whose\n"
            f"    # probe() succeeds at runtime (override with INFERENCE_DDR_BACKEND).\n"
            f"    file(GLOB _INFERENCE_DDR_BACKENDS CONFIGURE_DEPENDS\n"
            f"         \"${{CMAKE_CURRENT_SOURCE_DIR}}/src/ddr/*.c\")\n"
            f"    target_sources(inference PRIVATE\n"
            f"        src/inference_prof.c\n"
            f"        src/inference_ddr.c\n"
            f"        ${{_INFERENCE_DDR_BACKENDS}})\n"
            f"    target_compile_definitions(inference PUBLIC INFERENCE_PROFILING=1)\n"
            f"    message(STATUS\n"
            f"        \"inference: per-layer profiling ENABLED (INFERENCE_PROFILING=1)\")\n"
            f"else()\n"
            f"    message(STATUS\n"
            f"        \"inference: per-layer profiling disabled \"\n"
            f"        \"(cmake -DINFERENCE_PROFILING=ON to enable)\")\n"
            f"endif()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Smoke test (requires hardware to run; built by default)\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Override UIO instance names at configure time, e.g.:\n"
            + "".join(
                f"#   cmake -D{kd.instance_macro}={kd.uio_default} ...\n"
                for kd in active
            ) +
            f"# Disable: cmake -DINFERENCE_BUILD_TEST=OFF ...\n"
            f"option(INFERENCE_BUILD_TEST\n"
            f"       \"Build test_inference smoke test\" ON)\n"
            f"if(INFERENCE_BUILD_TEST)\n"
            f"    add_executable(test_inference test/test_inference.c)\n"
            f"    target_link_libraries(test_inference PRIVATE inference)\n"
            f"    target_compile_options(test_inference PRIVATE -Wall -Wextra -O2)\n"
            f"{instance_overrides}\n"
            f"    message(STATUS\n"
            f"        \"inference: test_inference will be built \"\n"
            f"        \"(disable: -DINFERENCE_BUILD_TEST=OFF)\")\n"
            f"endif()\n"
        )

    def _cmake_host_ops(self) -> str:
        """Extra build settings when the model has host-CPU ops: libm, and no
        FMA contraction so the double arithmetic rounds exactly like the
        scheduler's simulation (the source also carries a pragma).  Empty
        for models without host ops, so their CMakeLists is unchanged."""
        if not getattr(self, "_host_nodes", None):
            return ""
        return (
            "\n"
            "# Host-CPU ops (Softmax / LayerNorm / GELU / ...): libm, and no FMA\n"
            "# contraction so results match the scheduler's simulation bit for bit.\n"
            "target_compile_options(inference PRIVATE -ffp-contract=off)\n"
            "target_link_libraries(inference PUBLIC m)\n"
        )

