#!/usr/bin/env python3
"""generate_tts_project.py — the Piper voice + calibrated exponents -> the KV260
project behind libpiper_tts.so (doc/plans/TTS_PLAN.md §4).

  1. src/piper.py: the ``chunk`` entry (flow + HiFi-GAN decoder of 128
     frames, 1.49 s of audio) with every exponent of piper_study.py
     calibrate, and the text encoder's ``encode_<T>`` entries (ids padded
     to T in ENC_BUCKETS; piper_study.py encoder's exponents)
  2. inference-scheduler: OnnxGraph + CodeGenerator -> <out>/ (CMake
     project, weights/*.dat)
  3. driver/ for ConvKernel and VectorOPKernel (the decoder's residual
     sums, doc/plans/OFFLOAD_PLAN.md §2.2), test/tts_api.{c,h} +
     test/tts_dp.{c,h} + test/tts_bench.c + test/tts_glue.h (inference_init
     with the project's kernels, the encode buckets and their run
     functions), CMake targets tts_bench and piper_tts (libpiper_tts.so:
     only the tts_* symbols exported), project.json, layers.json
  4. weights/dp.dat (the C duration predictor's weights, read by
     tts_open) and weights/voice.json (phoneme ids, espeak voice, sampling
     defaults) for the chat server's front end (demo/chat/piper_backend.py)

usage: inference-scheduler/.venv/bin/python demo/tts/scripts/generate_tts_project.py
           [--assets DIR] [--out-dir demo/tts/build/piper_project] [--driver-dirs JSON]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, os.path.join(REPO, "inference-scheduler"))

from src.codegen.multi import MultiEntryGenerator       # noqa: E402
from src.graph import OnnxGraph                         # noqa: E402
from src.matmul_lowering import shared_weight_layouts    # noqa: E402
from src.piper import (ENC_BUCKETS, PiperChunkFrontend, PiperEncoderFrontend,   # noqa: E402
                       entry_info, load_weights)
import piper_vits as pv                                 # noqa: E402

DEFAULT_ASSETS = os.path.join(REPO, "demo", "tts", "assets", "piper-lessac-medium")
DEFAULT_OUT = os.path.join(REPO, "demo", "tts", "build", "piper_project")
SRC = os.path.join(REPO, "demo", "tts", "src")
C_SOURCES = ("tts_api.c", "tts_api.h", "tts_bench.c", "tts_dp.c", "tts_dp.h")   # + the generated test/tts_glue.h


def driver_dirs_from_config(path: str) -> dict:
    """local.driver_dirs of demo/bert_squad/bert_squad_config.json."""
    if not os.path.exists(path):
        return {}
    cfg = json.load(open(path))
    base = os.path.dirname(os.path.abspath(path))
    out = {}
    for k, v in (cfg.get("local", {}).get("driver_dirs") or {}).items():
        if k.startswith("_") or not v:
            continue
        v = os.path.expanduser(v)
        out[k] = v if os.path.isabs(v) else os.path.normpath(os.path.join(base, v))
    return out


def populate_drivers(out: str, driver_dirs: dict, active) -> list:
    dst = os.path.join(out, "driver")
    os.makedirs(dst, exist_ok=True)
    missing = []
    for kd in active:
        src = driver_dirs.get(kd.name)
        for f in kd.driver_files:
            p = os.path.join(src, f) if src else None
            if p and os.path.exists(p):
                shutil.copy2(p, os.path.join(dst, f))
            else:
                missing.append(f"{kd.name}/{f}")
    return missing


def write_voice(out: str, voice_json: str) -> None:
    """weights/voice.json (phoneme ids, espeak voice, sampling defaults) for
    the chat server's front end (demo/chat/piper_backend.py).  The text
    encoder and the duration predictor are the library's, so the server needs
    no weights of its own."""
    cfg = json.load(open(voice_json))
    voice = {k: cfg[k] for k in ("audio", "espeak", "inference", "phoneme_id_map", "language", "dataset")
             if k in cfg}
    voice["model"] = "piper-lessac-medium"
    with open(os.path.join(out, "weights", "voice.json"), "w") as f:
        json.dump(voice, f, indent=1, ensure_ascii=False)


def write_glue(out: str, buckets, dp_floats: int, active) -> None:
    """test/tts_glue.h: inference_init() with the project's kernels (``active``:
    the generator's active kernels), the encode_<T> buckets and a dispatcher to
    their run functions."""
    cases = "\n".join(f"    case {i}: inference_run_encode_{T}(ids, n, x, stats); return;"
                       for i, T in enumerate(buckets))
    text = (
        "/* tts_glue.h - generated by demo/tts/scripts/generate_tts_project.py: the text\n"
        " * encoder's encode_<T> entries (ids padded to T rows). */\n"
        "#ifndef TTS_GLUE_H\n#define TTS_GLUE_H\n\n"
        f"#define TTS_N_BUCKETS {len(buckets)}\n"
        f"#define TTS_MAX_IDS   {max(buckets)}\n"
        f"#define TTS_DP_FLOATS {dp_floats}   /* weights/dp.dat: piper_vits.dp_tensors() */\n"
        f"static const int tts_buckets[TTS_N_BUCKETS] = {{ {', '.join(str(b) for b in buckets)} }};\n\n"
        "/* inference_init() with every kernel the project drives (" + ", ".join(kd.name for kd in active)
        + ") */\nstatic int tts_glue_init(void)\n{\n"
        f"    return inference_init({', '.join(kd.instance_macro for kd in active)});\n}}\n\n"
        "static void tts_glue_encode(int b, const int32_t *ids, const int32_t *n, float *x, float *stats)\n"
        "{\n    switch (b) {\n" + cases + "\n    default: return;\n    }\n}\n\n#endif\n")
    with open(os.path.join(out, "test", "tts_glue.h"), "w") as f:
        f.write(text)


def patch_cmake(out: str, cg, info: dict) -> None:
    path = os.path.join(out, "CMakeLists.txt")
    text = open(path).read()
    macros = "\n".join(f"            {kd.instance_macro}" for kd in cg._active_kernels)
    text += (
        "\n"
        "# -----------------------------------------------------------------------\n"
        "# tts_bench — the board gate runner, and piper_tts — libpiper_tts.so for\n"
        "# the chat server, both over test/tts_api.c (added by\n"
        "# demo/tts/scripts/generate_tts_project.py).  Only the tts_* symbols of\n"
        "# the shared library are exported.\n"
        "# -----------------------------------------------------------------------\n"
        "if(INFERENCE_TARGET STREQUAL \"LINUX\")\n"
        "    set_property(TARGET inference PROPERTY POSITION_INDEPENDENT_CODE ON)\n"
        "    add_executable(tts_bench test/tts_bench.c test/tts_api.c test/tts_dp.c)\n"
        "    target_link_libraries(tts_bench PRIVATE inference m pthread)\n"
        "    add_library(piper_tts SHARED test/tts_api.c test/tts_dp.c)\n"
        "    target_link_libraries(piper_tts PRIVATE inference m pthread)\n"
        "    target_link_options(piper_tts PRIVATE -Wl,--exclude-libs,ALL -Wl,--no-undefined)\n"
        "    foreach(_tgt IN ITEMS tts_bench piper_tts)\n"
        "        target_include_directories(${_tgt} PRIVATE test)\n"
        "        target_compile_options(${_tgt} PRIVATE -Wall -Wextra -O2 -ffp-contract=off)   # tts_dp.c: no FMA\n"
        "        target_compile_definitions(${_tgt} PRIVATE\n"
        "            TTS_API_WEIGHTS_DIR=\"${INFERENCE_WEIGHTS_DIR}\"\n"
        f"            TTS_MODEL_NAME=\"{info['model_name']}\" TTS_SAMPLE_RATE={info['sample_rate']})\n"
        "        foreach(_macro IN ITEMS\n"
        f"{macros})\n"
        "            if(DEFINED ${_macro})\n"
        "                target_compile_definitions(${_tgt} PRIVATE ${_macro}=${${_macro}})\n"
        "            endif()\n"
        "        endforeach()\n"
        "    endforeach()\n"
        "endif()\n")
    with open(path, "w") as f:
        f.write(text)


def vsmx_default() -> bool:
    """The encoder's attention softmax on VectorOPKernel's softmax unit
    (doc/plans/SOFTMAX_PLAN.md §5) where the platform has the unit."""
    from src.smx_nodes import enabled
    return enabled()


def entry_graphs(assets: str, W: dict = None, vsmx: bool = None) -> list:
    """[(entry, OnnxGraph)] of libpiper_tts.so in project order: "chunk", then
    "encode_<T>" for every bucket of ENC_BUCKETS.  Also what
    inference-scheduler/perf_calibrate.py prices, so its kernel calls are the
    library's (``vsmx`` None: vsmx_default())."""
    return _entries(assets, W, vsmx)[0]


def _entries(assets: str, W: dict = None, vsmx: bool = None):
    """(entry_graphs, the chunk entry's info: frames, sample rate, ...)."""
    vsmx = vsmx_default() if vsmx is None else bool(vsmx)
    if W is None:
        W = load_weights(os.path.join(assets, "en_US-lessac-medium.onnx"))
    doc = json.load(open(os.path.join(assets, "exponents.json")))
    if "encoder" not in doc:
        raise SystemExit("exponents.json has no \"encoder\" exponents: run piper_study.py encoder first")
    model = PiperChunkFrontend(W, doc["exponents"], name="piper_lessac_medium").entry()
    g = OnnxGraph(model, fuse_act=True, s2d_stem=True)
    # the encoder's MatMul weights live in ConvKernel's x image of a kernel
    # width: the largest bucket plans the widths, the others reuse them, so
    # the project keeps one copy of every weight (as src/llm_entries.py)
    enc, kw = {}, None
    for T in sorted(ENC_BUCKETS, reverse=True):
        eg = OnnxGraph(PiperEncoderFrontend(W, doc["encoder"], T, name="piper_lessac_medium",
                                            vsmx=vsmx).entry(), matmul_conv_kw=kw)
        if kw is None:
            kw = shared_weight_layouts(eg.nodes)
        enc[T] = eg
    return [("chunk", g)] + [(f"encode_{T}", enc[T]) for T in ENC_BUCKETS], entry_info(model)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n\n")[0])
    ap.add_argument("--assets", default=DEFAULT_ASSETS)
    ap.add_argument("--out-dir", default=DEFAULT_OUT)
    ap.add_argument("--driver-dirs", default=None,
                    help="JSON {kernel: dir}; default: local.driver_dirs of "
                         "demo/bert_squad/bert_squad_config.json")
    ap.add_argument("--vsmx", choices=("auto", "on", "off"), default="auto",
                    help="the text encoder's attention softmax on VectorOPKernel's softmax unit "
                         "(doc/plans/SOFTMAX_PLAN.md §5); auto: where the platform has the unit "
                         "(kernels.vectorop.softmax)")
    a = ap.parse_args(argv)
    t0 = time.time()
    vsmx = vsmx_default() if a.vsmx == "auto" else a.vsmx == "on"
    W = load_weights(os.path.join(a.assets, "en_US-lessac-medium.onnx"))
    entries, info = _entries(a.assets, W, vsmx)
    g = entries[0][1]
    cg = MultiEntryGenerator(entries, "piper_lessac_medium")
    out = os.path.abspath(a.out_dir)
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(out)
    summary = cg.write_project(out)
    dd = json.loads(a.driver_dirs) if a.driver_dirs else driver_dirs_from_config(
        os.path.join(REPO, "demo", "bert_squad", "bert_squad_config.json"))
    missing = populate_drivers(out, dd, cg._active_kernels)
    for name in C_SOURCES:
        shutil.copy2(os.path.join(SRC, name), os.path.join(out, "test", name))
    dp = pv.dp_flat(W)                                    # the C duration predictor's weights
    dp.astype("<f4").tofile(os.path.join(out, "weights", "dp.dat"))
    write_glue(out, ENC_BUCKETS, int(dp.size), cg._active_kernels)
    write_voice(out, os.path.join(a.assets, "en_US-lessac-medium.onnx.json"))
    patch_cmake(out, cg, {"model_name": "piper-lessac-medium", "sample_rate": info["sample_rate"]})
    layers, base = [], 0                  # MultiEntryGenerator numbers the nodes globally
    for ename, eg in entries:
        if eg.nodes[0].index != base:
            raise RuntimeError(f"entry {ename}: first layer {eg.nodes[0].index}, expected {base}")
        layers += [{"i": sn.index, "entry": ename, "name": sn.onnx_node.name, "op": sn.onnx_node.op_type,
                    "kind": "conv" if sn.kernel_name == "ConvKernel" else sn.onnx_node.op_type}
                   for sn in eg.nodes]
        base += len(eg.nodes)
    json.dump(layers, open(os.path.join(out, "layers.json"), "w"), indent=0)
    summary.update({"model": "piper-lessac-medium", "entry": info, "assets": os.path.abspath(a.assets),
                    "nodes": len(g.nodes), "encode_buckets": list(ENC_BUCKETS),
                    "encode_nodes": {n: len(eg.nodes) for n, eg in entries[1:]}, "vsmx": vsmx,
                    "missing_drivers": missing, "generated_s": round(time.time() - t0, 1)})
    json.dump(summary, open(os.path.join(out, "project.json"), "w"), indent=2)
    print(f"project: {out} ({len(g.nodes)} nodes, pool {summary['pool_bytes'] / 2**20:.1f} MiB, "
          f"{summary['generated_s']} s)" + (f"; missing drivers: {missing}" if missing else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
