#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# gen_smx_rom.py — writes rtl/vo_smx_rom.sv, the exponential table of the RTL
# VectorOPKernel's softmax (vo_smx; doc/plans/SOFTMAX_PLAN.md §2.1), and checks it.
#
#     TAB[k] = round(2^16 * 2^(-k / 4096)),  k = 0 .. 4095   (17 bits, TAB[0] = 65536)
#
# rounded to nearest, ties to even — the table of the specification
# inference-scheduler/src/vectorop_smx.py and of the C++ model
# (kernels/vectorop/include/VectorOP.h smx_table).  Every run asserts that the
# two Python computations agree and that no entry lies within 1e-6 of a
# rounding tie, so any exp2 within a few ulp gives the same table (the C++
# model's std::exp2 among them).
#
#   gen_smx_rom.py               write rtl/vo_smx_rom.sv
#   gen_smx_rom.py --check       exit 1 if rtl/vo_smx_rom.sv is not what it writes
# ---------------------------------------------------------------------------
import argparse
import importlib.util
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "rtl", "vo_smx_rom.sv")
SPEC = os.path.join(HERE, "..", "..", "..", "inference-scheduler", "src", "vectorop_smx.py")
GENERATOR = "kernels/vectorop_rtl/scripts/gen_smx_rom.py"

F = 12
E = 16
ROM_D = 1 << F
ROM_W = E + 1
MIN_TIE_MARGIN = 1e-6


def table():
    tab = []
    for k in range(ROM_D):
        v = math.ldexp(2.0 ** (-k / ROM_D), E)
        margin = abs(abs(v - math.floor(v)) - 0.5)
        if margin < MIN_TIE_MARGIN:
            sys.exit(f"TAB[{k}] = {v!r} lies {margin:.3g} from a rounding tie")
        tab.append(round(v))
    spec = importlib.util.spec_from_file_location("vectorop_smx", SPEC)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if [int(x) for x in mod.TAB] != tab or (mod.F, mod.E) != (F, E):
        sys.exit(f"the table differs from {SPEC}'s TAB")
    return tab


def render(tab):
    inits, line = [], []
    for a, v in enumerate(tab):
        line.append(f"rom[{a:4d}] = 17'd{v:<5d};")
        if len(line) == 5:
            inits.append("    " + " ".join(line))
            line = []
    if line:
        inits.append("    " + " ".join(line))
    return f"""// ---------------------------------------------------------------------------
// vo_smx_rom — GENERATED by {GENERATOR}; do not edit.
//
// The softmax's exponential (vo_smx): rom[k] = round(2^16 * 2^(-k / 4096)),
// k = 0 .. 4095 (round to nearest, ties to even; doc/plans/SOFTMAX_PLAN.md
// §2.1).  Two read ports, two cycles of latency (the block RAM and its output
// register): two BRAM36 (4K x 9 each) per two lanes.
// ---------------------------------------------------------------------------
module vo_smx_rom (
  input  logic        clk,
  input  logic [11:0] addr_a,
  input  logic [11:0] addr_b,
  output logic [16:0] q_a,
  output logic [16:0] q_b
);
  (* rom_style = "block" *) logic [16:0] rom [{ROM_D}];
  logic [16:0] r_a, r_b;

  initial begin
{chr(10).join(inits)}
  end

  always_ff @(posedge clk) begin
    r_a <= rom[addr_a];
    r_b <= rom[addr_b];
    q_a <= r_a;                             // the block RAM's output register
    q_b <= r_b;
  end
endmodule
"""


def main():
    ap = argparse.ArgumentParser(description="Write / check rtl/vo_smx_rom.sv (vo_smx's exponential table).")
    ap.add_argument("--check", action="store_true", help="compare with rtl/vo_smx_rom.sv")
    args = ap.parse_args()
    text = render(table())
    if args.check:
        have = open(OUT).read() if os.path.exists(OUT) else ""
        if have != text:
            print(f"{OUT} is stale: run {GENERATOR}", file=sys.stderr)
            return 1
        print(f"{OUT}: up to date ({ROM_D} x {ROM_W})")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT} ({ROM_D} x {ROM_W})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
