"""
Central registry of hardware kernels.

To add a new kernel:
  1. Append a KernelDesc entry to KERNEL_REGISTRY (this file).
  2. Implement a KernelNode subclass in nodes.py with matching kernel_name.

Everything else — driver file selection, CMakeLists, inference_init() signature,
UIO device name macros — is derived automatically from the registry.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import List, Tuple


__all__ = ["KernelDesc", "KERNEL_REGISTRY"]


@dataclass(frozen=True)
class KernelDesc:
    """Describes a single hardware accelerator kernel."""

    name: str          # "VectorOPKernel"    — matches node.kernel_name
    driver_prefix: str # "xvectoropkernel"   — lowercase filename prefix
    c_type: str        # "XVectoropkernel"   — C struct type from driver header
    uio_default: str   # "VectorOPKernel_0"  — UIO sysfs name (DT node label)
    axi_base: int      # 0xA000_0000         — AXI-Lite ctrl register base

    # Driver source file names (relative, copied into project driver/)
    driver_files: Tuple[str, ...] = ()
    driver_readme: str = ""

    @property
    def c_var(self) -> str:
        """Static C instance variable name, e.g. 's_vectoropkernel'."""
        return f"s_{self.name.lower()}"

    @property
    def init_param(self) -> str:
        """C parameter name for inference_init(), e.g. 'vectoropkernel_instance'."""
        return f"{self.name.lower()}_instance"

    @property
    def instance_macro(self) -> str:
        """CMake / C preprocessor macro for the UIO device name override.
        e.g. 'INFERENCE_VECTOROPKERNEL_INSTANCE'."""
        return f"INFERENCE_{self.name.upper()}_INSTANCE"


# ---------------------------------------------------------------------------
# VectorOPKernel
# ---------------------------------------------------------------------------

_VECTOROP_DRIVER_FILES: Tuple[str, ...] = (
    "xvectoropkernel.h",
    "xvectoropkernel_hw.h",
    "xvectoropkernel.c",
    "xvectoropkernel_sinit.c",   # BARE_METAL target
    "xvectoropkernel_linux.c",   # LINUX target
)

_VECTOROP_README = """\
# driver/

Place XVectoropkernel driver sources here before building.

Required files:
  xvectoropkernel.h
  xvectoropkernel_hw.h
  xvectoropkernel.c
  xvectoropkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xvectoropkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are the RTL VectorOPKernel's driver (the HLS driver's API), written by
kernels/vectorop_rtl/scripts/gen_driver.py.  Generate them in the axi_demo
build directory (build/):

  make driver_vectorop_rtl

then copy them from

  <axi_demo>/build/kernels/vectorop_rtl/driver/VectorOPKernel_v1_0/src/

or re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kernels/vectorop_rtl/driver/VectorOPKernel_v1_0/src
"""

# ---------------------------------------------------------------------------
# MatmulKernel
# ---------------------------------------------------------------------------

_MATMUL_DRIVER_FILES: Tuple[str, ...] = (
    "xmatmulkernel.h",
    "xmatmulkernel_hw.h",
    "xmatmulkernel.c",
    "xmatmulkernel_sinit.c",     # BARE_METAL target
    "xmatmulkernel_linux.c",     # LINUX target
)

_MATMUL_README = """\
# driver/

Place XMatmulkernel driver sources here before building.

Required files:
  xmatmulkernel.h
  xmatmulkernel_hw.h
  xmatmulkernel.c
  xmatmulkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xmatmulkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are the RTL MatmulKernel's driver (the HLS driver's API), written by
kernels/matmul_rtl/scripts/gen_driver.py.  Generate them in the axi_demo
build directory (build/):

  make driver_matmul_rtl

then copy them from

  <axi_demo>/build/kernels/matmul_rtl/driver/MatmulKernel_v1_0/src/

or re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kernels/matmul_rtl/driver/MatmulKernel_v1_0/src
"""

# ---------------------------------------------------------------------------
# ConvKernel
# ---------------------------------------------------------------------------

_CONV_DRIVER_FILES: Tuple[str, ...] = (
    "xconvkernel.h",
    "xconvkernel_hw.h",
    "xconvkernel.c",
    "xconvkernel_sinit.c",    # BARE_METAL target
    "xconvkernel_linux.c",    # LINUX target
)

_CONV_README = """\
# driver/

Place XConvkernel driver sources here before building.

Required files:
  xconvkernel.h
  xconvkernel_hw.h
  xconvkernel.c
  xconvkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xconvkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are generated by Vitis HLS synthesis. Copy them from:

  <axi_demo>/build/kernels/conv/kv260/conv_kv260/hls/impl/ip/
             drivers/ConvKernel_v1_0/src/

or run from the axi_demo build directory (build/):

  make synthesize_conv_kv260

then re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kernels/conv/kv260/conv_kv260/hls/impl/ip/\\
               drivers/ConvKernel_v1_0/src
"""

# ---------------------------------------------------------------------------
# PoolKernel
# ---------------------------------------------------------------------------

_POOL_DRIVER_FILES: Tuple[str, ...] = (
    "xpoolingkernel.h",
    "xpoolingkernel_hw.h",
    "xpoolingkernel.c",
    "xpoolingkernel_sinit.c",    # BARE_METAL target
    "xpoolingkernel_linux.c",    # LINUX target
)

_POOL_README = """\
# driver/

Place XPoolingkernel driver sources here before building.

Required files:
  xpoolingkernel.h
  xpoolingkernel_hw.h
  xpoolingkernel.c
  xpoolingkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xpoolingkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are the RTL PoolingKernel's driver (the HLS driver's API), written by
kernels/pool_rtl/scripts/gen_driver.py.  Generate them in the axi_demo
build directory (build/):

  make driver_pool_rtl

then copy them from

  <axi_demo>/build/kernels/pool_rtl/driver/PoolingKernel_v1_0/src/

or re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kernels/pool_rtl/driver/PoolingKernel_v1_0/src
"""

# ---------------------------------------------------------------------------
# Registry — ordered dict; iteration order defines init order in generated C.
# To add a new kernel, append a new entry here.
# ---------------------------------------------------------------------------

KERNEL_REGISTRY: dict = {
    "VectorOPKernel": KernelDesc(
        name="VectorOPKernel",
        driver_prefix="xvectoropkernel",
        c_type="XVectoropkernel",
        uio_default="VectorOPKernel_0",
        axi_base=0xA000_0000,
        driver_files=_VECTOROP_DRIVER_FILES,
        driver_readme=_VECTOROP_README,
    ),
    "MatmulKernel": KernelDesc(
        name="MatmulKernel",
        driver_prefix="xmatmulkernel",
        c_type="XMatmulkernel",
        uio_default="MatmulKernel_0",
        axi_base=0xA001_0000,
        driver_files=_MATMUL_DRIVER_FILES,
        driver_readme=_MATMUL_README,
    ),
    "ConvKernel": KernelDesc(
        name="ConvKernel",
        driver_prefix="xconvkernel",
        c_type="XConvkernel",
        uio_default="ConvKernel_0",
        axi_base=0xA002_0000,
        driver_files=_CONV_DRIVER_FILES,
        driver_readme=_CONV_README,
    ),
    "PoolKernel": KernelDesc(
        name="PoolKernel",
        driver_prefix="xpoolingkernel",
        c_type="XPoolingkernel",
        uio_default="PoolKernel_0",
        axi_base=0xA003_0000,
        driver_files=_POOL_DRIVER_FILES,
        driver_readme=_POOL_README,
    ),
}


def all_driver_files() -> List[str]:
    """All driver file names across all registered kernels (for multi-kernel projects)."""
    files: List[str] = []
    seen = set()
    for kd in KERNEL_REGISTRY.values():
        for f in kd.driver_files:
            if f not in seen:
                seen.add(f)
                files.append(f)
    return files


def mixed_driver_readme(kernel_names: List[str]) -> str:
    """Generate a combined driver/README.md for projects using multiple kernels."""
    sections = []
    for name in kernel_names:
        kd = KERNEL_REGISTRY[name]
        rtl = {"MatmulKernel": "matmul", "VectorOPKernel": "vectorop", "PoolKernel": "pool"}.get(kd.name)
        source = (f"make driver_{rtl}_rtl (the SystemVerilog kernel's driver)"
                  if rtl else f"Vitis HLS synthesis output for {kd.name}")
        sections.append(
            f"## {kd.name} driver\n\n"
            + "\n".join(f"  {f}" for f in kd.driver_files)
            + f"\n\nSource: {source}.\n"
            f"AXI-Lite base address: 0x{kd.axi_base:08X}\n"
            f"UIO device name:       {kd.uio_default}\n"
        )
    return (
        "# driver/\n\n"
        "This project uses multiple hardware kernels. Place all driver\n"
        "sources from each kernel below before building.\n\n"
        + "\n".join(sections)
    )
