// ---------------------------------------------------------------------------
// vo_act — the LeakyReLU / SiLU / GELU / GELU tanh activations (VectorOP.h
// ACT_LEAKY_RELU .. ACT_GELU_TANH: the act register, or an activation op's
// own) on the 8-lane result words, after the ALU and DIV paths merge.  A
// fixed pipeline of LAT = 7 cycles; other jobs pass through it unchanged.
//
//   LeakyReLU          x >= 0 ? x : round(x * alpha / 2^16)
//                      (a DSP48E2 per lane; the rounding — to nearest, ties
//                      to even — on the 33-bit product in fabric)
//   SiLU, GELU (tanh)  max(x, 0) - rom[BASE + |x|]  for |x| < LEN, else max(x, 0)
//                      (vo_act_rom, generated by scripts/gen_act_rom.py: one
//                      two-port block ROM per two lanes)
//
// Stages (registers): 0 input; 1 |x|, the DSP's A / B registers; 2 the ROM
// address and the past-the-table flag, M; 3 the ROM read, P; 4 the ROM's
// output register, the product's floor and round-up bit; 5 the table result
// and the rounded product; 6 the function's select.
// ---------------------------------------------------------------------------
module vo_act
  import vo_pkg::*;
  import vo_act_tab::*;
(
  input  logic          clk,
  input  logic          rst,
  input  logic [2:0]    fn,                 // job constants: ACT_* code (0 none, 3..6)
  input  logic [15:0]   alpha,              // LeakyReLU slope, alpha / 2^16

  input  logic          in_valid,
  input  logic [BW-1:0] in_data,
  output logic          out_valid,
  output logic [BW-1:0] out_data
);
  localparam int LAT = 7;

  // Job constants (fn / alpha do not change during a job).
  logic [1:0]         mode;                 // 0 pass, 1 LeakyReLU, 2 table
  logic [11:0]        tbase, tlen;
  logic signed [16:0] alpha_s;              // the DSP's B operand, 0 <= alpha < 1
  always_ff @(posedge clk) begin
    mode    <= (fn == 3'(ACT_LEAKY_RELU)) ? 2'd1 :
               (fn == 3'(ACT_SILU) || fn == 3'(ACT_GELU) || fn == 3'(ACT_GELU_TANH)) ? 2'd2 : 2'd0;
    tbase   <= (fn == 3'(ACT_GELU)) ? GELU_BASE : (fn == 3'(ACT_GELU_TANH)) ? GELU_TANH_BASE : SILU_BASE;
    tlen    <= (fn == 3'(ACT_GELU)) ? GELU_LEN  : (fn == 3'(ACT_GELU_TANH)) ? GELU_TANH_LEN  : SILU_LEN;
    alpha_s <= {1'b0, alpha};
  end

  logic [LAT-1:0] v;
  always_ff @(posedge clk) begin
    if (rst) v <= '0;
    else     v <= {v[LAT-2:0], in_valid};
  end
  assign out_valid = v[LAT-1];

  logic [11:0]   addr2 [E];
  logic [6:0]    m4    [E];                 // the ROM's magnitude, stage 4
  logic [15:0]   o6    [E];

  for (genvar k = 0; k < E / 2; k++) begin : g_rom
    vo_act_rom u_rom (
      .clk,
      .addr_a (addr2[2*k]), .addr_b (addr2[2*k+1]),
      .q_a    (m4[2*k]),    .q_b    (m4[2*k+1])
    );
  end

  for (genvar l = 0; l < E; l++) begin : g_lane
    logic [15:0]        x0, x1, x2, x3, x4, x5;
    logic [15:0]        mag1;
    logic               far2, far3, far4;
    logic signed [15:0] da;                 // DSP A register
    logic signed [16:0] db;                 // DSP B register
    logic signed [32:0] dm, dp;             // DSP M and P registers
    logic [15:0]        q4, y5, lk5;
    logic               up4;
    logic               unused_dp;
    assign unused_dp = dp[32];              // |x * alpha| < 2^31

    always_ff @(posedge clk) begin
      // 0
      x0    <= in_data[EW*l +: EW];
      // 1
      x1    <= x0;
      mag1  <= x0[15] ? 16'(-x0) : x0;      // |-32768| = 0x8000 as unsigned
      da    <= x0;
      db    <= alpha_s;
      // 2
      x2       <= x1;
      far2     <= (mag1[15:12] != '0) || (mag1[11:0] >= tlen);
      addr2[l] <= tbase + mag1[11:0];
      dm       <= da * db;
      // 3 (ROM read)
      x3    <= x2;
      far3  <= far2;
      dp    <= dm;
      // 4 (ROM output register): floor(x * alpha / 2^16) and its round-up bit
      // (above half, or exactly half with an odd floor)
      x4    <= x3;
      far4  <= far3;
      q4    <= dp[31:16];
      up4   <= dp[15] && ((dp[14:0] != '0) || dp[16]);
      // 5
      x5    <= x4;
      y5    <= (x4[15] ? 16'h0 : x4) - (far4 ? 16'h0 : {9'h0, m4[l]});
      lk5   <= q4 + 16'(up4);
      // 6
      o6[l] <= (mode == 2'd2) ? y5 : (mode == 2'd1 && x5[15]) ? lk5 : x5;
    end
  end

  always_comb for (int l = 0; l < E; l++) out_data[EW*l +: EW] = o6[l];


endmodule
