"""Tests for MatmulKernel scheduler integration — hardware-bound
validation and platform-JSON resolver.

The matmul-model ONNX files generated by ``gen_matmul_models.py`` are
exercised on hardware via ``run_remote_tests.py``; the corresponding
Python-side correctness is covered by ``test_mixed_kernel.py`` and
friends.  This module focuses specifically on rejecting layer
geometries the kernel cannot service (``k > kMaxK``) and on the
single-source-of-truth resolver that reads ``kernels.matmul`` from
the platform JSON.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.graph import OnnxGraph
from src.nodes import MatmulNode, SchedulerError


MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")


def _matmul_model(name: str) -> str:
    return os.path.join(MODELS_DIR, name)


def _matmul_models_exist() -> bool:
    return (os.path.isfile(_matmul_model("mm_unsupported_k.onnx")) and
            os.path.isfile(_matmul_model("mm_k_at_limit.onnx")))


# ---------------------------------------------------------------------------
# MatmulNode hardware-bound validation
#
# kMaxK comes from platforms/<AXI_PLATFORM>.json (see _matmul_hw_config)
# and matches the kernel's compile-time ``a_buf[kTileN][kMaxK]`` row
# staging buffer.  A matmul with k > kMaxK has no runtime fallback —
# reject it at parse time with an error that names the bound and the
# JSON field to bump.
# ---------------------------------------------------------------------------

@unittest.skipUnless(_matmul_models_exist(),
                     "Run test/gen_matmul_models.py first")
class TestMatmulNodeHardwareBounds(unittest.TestCase):
    """MatmulNode rejects matmuls the kernel cannot service."""

    def test_k_too_large_raises(self):
        """k == kMaxK + 1 violates the bound by one unit."""
        from src._matmul_hw_config import MATMUL_MAX_K
        with self.assertRaises(SchedulerError) as cm:
            OnnxGraph(_matmul_model("mm_unsupported_k.onnx"))
        msg = str(cm.exception)
        self.assertIn(f"k={MATMUL_MAX_K + 1}", msg)
        self.assertIn("kMaxK", msg)

    def test_k_at_limit_parses(self):
        """k == kMaxK must parse — bound is `≤`, not `<`."""
        from src._matmul_hw_config import MATMUL_MAX_K
        g = OnnxGraph(_matmul_model("mm_k_at_limit.onnx"))
        sn = g.nodes[0]
        self.assertIsInstance(sn, MatmulNode)
        self.assertEqual(sn.k, MATMUL_MAX_K)


class TestMatmulHwConfigResolver(unittest.TestCase):
    """The hardware-bound resolver reads from the platform JSON
    (platforms/<AXI_PLATFORM>.json), the same source the C++ CMake build
    consumes via ``matmul_load_constants()``.  Tests use the public
    ``resolve()`` function so failure paths can be probed without
    reloading the module — that would replace the
    ``MatmulHwConfigError`` class object and break ``assertRaises``."""

    def _platforms_dir(self):
        from pathlib import Path
        return (Path(__file__).resolve().parent.parent.parent / "platforms")

    def test_constants_match_kv260_json(self):
        """Resolved values match platforms/kv260.json's kernels.matmul —
        guards against drift between the Python validator and the JSON
        the C++ build reads."""
        import json

        from src._matmul_hw_config import MATMUL_MAX_K
        with (self._platforms_dir() / "kv260.json").open() as f:
            cfg = json.load(f)["kernels"]["matmul"]
        self.assertEqual(MATMUL_MAX_K, cfg["max_k"])

    def test_resolve_alternate_platform_picks_up_overrides(self):
        """``resolve('<name>')`` reads ``platforms/<name>.json`` — same
        mechanism the CMake build uses when ``-DAXI_PLATFORM=<name>``
        is passed."""
        import json
        from src._matmul_hw_config import resolve

        alt = self._platforms_dir() / "_test_matmul_override.json"
        alt.write_text(json.dumps({
            "description": "test-only override",
            "part": "x", "clock": 100,
            "kernels": {"matmul": {
                "tile_n": 4, "tile_m": 16, "tile_k": 256,
                "max_k": 1024,                      # <-- the override
            }},
        }))
        try:
            cfg = resolve("_test_matmul_override")
            self.assertEqual(cfg["MATMUL_MAX_K"], 1024)
        finally:
            alt.unlink(missing_ok=True)

    def test_missing_platform_file_raises(self):
        """``resolve()`` with an unknown platform name must error loudly
        rather than silently fall back to defaults."""
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        with self.assertRaises(MatmulHwConfigError) as cm:
            resolve("_does_not_exist_xyzzy_matmul")
        self.assertIn("not found", str(cm.exception))

    def test_missing_kernels_matmul_section_raises(self):
        """A platform JSON with no ``kernels.matmul`` object must error —
        no silent default fallback."""
        import json
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        bad = self._platforms_dir() / "_test_no_matmul_section.json"
        bad.write_text(json.dumps({"description": "no kernels section",
                                   "part": "x", "clock": 100}))
        try:
            with self.assertRaises(MatmulHwConfigError) as cm:
                resolve("_test_no_matmul_section")
            self.assertIn("kernels.matmul", str(cm.exception))
        finally:
            bad.unlink(missing_ok=True)

    def test_missing_required_field_raises(self):
        """A platform JSON missing the mandatory ``kernels.matmul.max_k``
        field must error and name the missing field."""
        import json
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        bad = self._platforms_dir() / "_test_matmul_missing_field.json"
        bad.write_text(json.dumps({
            "description": "missing max_k",
            "part": "x", "clock": 100,
            "kernels": {"matmul": {
                "tile_n": 4, "tile_m": 16, "tile_k": 256,
                # max_k deliberately absent
            }},
        }))
        try:
            with self.assertRaises(MatmulHwConfigError) as cm:
                resolve("_test_matmul_missing_field")
            self.assertIn("max_k", str(cm.exception))
        finally:
            bad.unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()


# ---------------------------------------------------------------------------
# Packed tile-major B (MATMUL_OPTIMISATION §3b)
#
# A constant B is emitted in MatmulKernel's [ceil(M/kTileM)][K][kTileM]
# layout and the node is called with b_packed = 1; activations and
# constants shared with non-MatMul readers stay row-major.
# ---------------------------------------------------------------------------
import tempfile
import numpy as np
import onnx
from onnx import helper as oh, TensorProto as TP
from src._matmul_hw_config import MATMUL_TILE_M
from src.nodes import matmul_packed_m


def _build(nodes, inputs, outputs, inits):
    g = oh.make_graph(nodes, "t", inputs, outputs, initializer=inits)
    m = oh.make_model(g, opset_imports=[oh.make_opsetid("", 13)]); m.ir_version = 8
    d = tempfile.mkdtemp(); path = os.path.join(d, "m.onnx"); onnx.save(m, path)
    return path


def _const(name, arr):
    return oh.make_tensor(name, TP.FLOAT, arr.shape, arr.astype(np.float32).flatten().tolist())


class TestMatmulPackedB(unittest.TestCase):
    def test_constant_b_is_packed(self):
        k, m = 20, 10
        w = np.arange(k * m, dtype=np.float32).reshape(k, m) / 64.0
        path = _build([oh.make_node("MatMul", ["A", "W"], ["Y"])],
                      [oh.make_tensor_value_info("A", TP.FLOAT, [1, k])],
                      [oh.make_tensor_value_info("Y", TP.FLOAT, [1, m])], [_const("W", w)])
        g = OnnxGraph(path)
        node = [n for n in g.nodes if isinstance(n, MatmulNode)][0]
        self.assertTrue(node.b_packed)
        pm = matmul_packed_m(m)
        self.assertEqual(pm, MATMUL_TILE_M)
        packed = node.inputs[1].packed_data
        self.assertEqual(packed.size, k * pm)
        img = packed.reshape(pm // MATMUL_TILE_M, k, MATMUL_TILE_M)
        for kk in range(k):
            for mm in range(m):
                self.assertEqual(img[mm // MATMUL_TILE_M, kk, mm % MATMUL_TILE_M], w[kk, mm])
            for mm in range(m, pm):
                self.assertEqual(img[0, kk, mm], 0.0)
        self.assertIn(f"{int(node.b_packed)}u);", node.emit_call({}))
        self.assertTrue(node.emit_call({}).rstrip().endswith("1u);"))

    def test_batched_constant_b_strides_rescaled(self):
        b, k, m = 3, 8, 20
        w = np.random.RandomState(0).rand(b, k, m)
        path = _build([oh.make_node("MatMul", ["A", "W"], ["Y"])],
                      [oh.make_tensor_value_info("A", TP.FLOAT, [b, 2, k])],
                      [oh.make_tensor_value_info("Y", TP.FLOAT, [b, 2, m])], [_const("W", w)])
        node = [n for n in OnnxGraph(path).nodes if isinstance(n, MatmulNode)][0]
        self.assertTrue(node.b_packed)
        self.assertEqual(node.b_batch_stride, k * matmul_packed_m(m))
        self.assertEqual(node.inputs[1].packed_data.size, b * k * matmul_packed_m(m))

    def test_activation_b_stays_row_major(self):
        k, m = 8, 8
        path = _build([oh.make_node("MatMul", ["A", "B"], ["Y"])],
                      [oh.make_tensor_value_info("A", TP.FLOAT, [1, k]),
                       oh.make_tensor_value_info("B", TP.FLOAT, [k, m])],
                      [oh.make_tensor_value_info("Y", TP.FLOAT, [1, m])], [])
        node = [n for n in OnnxGraph(path).nodes if isinstance(n, MatmulNode)][0]
        self.assertFalse(node.b_packed)
        self.assertIsNone(node.inputs[1].packed_data)
        self.assertTrue(node.emit_call({}).rstrip().endswith("0u);"))

    def test_constant_shared_with_vectorop_stays_row_major(self):
        k, m = 8, 8
        w = np.ones((k, m), dtype=np.float32)
        path = _build([oh.make_node("MatMul", ["A", "W"], ["Y"]),
                       oh.make_node("Add", ["W", "X2"], ["Z"])],
                      [oh.make_tensor_value_info("A", TP.FLOAT, [1, k]),
                       oh.make_tensor_value_info("X2", TP.FLOAT, [k, m])],
                      [oh.make_tensor_value_info("Y", TP.FLOAT, [1, m]),
                       oh.make_tensor_value_info("Z", TP.FLOAT, [k, m])], [_const("W", w)])
        node = [n for n in OnnxGraph(path).nodes if isinstance(n, MatmulNode)][0]
        self.assertFalse(node.b_packed)
        self.assertIsNone(node.inputs[1].packed_data)
