#!/usr/bin/env python3
"""generate_project.py — the stereo_depth demo's KV260 inference project
(doc/plans/STEREO_PLAN.md).

  1. the LightStereo-S frontend (inference-scheduler/src/stereo.py) at the
     network's H x W: the checkpoint (assets/ckpt, read without torch) and the
     checked-in formats (lightstereo_s_formats.json) -> build/lightstereo_s.onnx
  2. inference-scheduler on it -> build/project; the graph is compiled as the
     frontend wrote it: no stem rewrite (the 3-channel stride-2 convs carry
     exponents), no activation fusion (the frontend places them), no
     fully-connected or MatMul-on-ConvKernel rewrites
  3. the kernels' driver sources (config local.driver_dirs) -> driver/
  4. src/stereo_pairs.c -> test/, its glue test/stereo_glue.h (buffer sizes,
     inference_init / inference_run shims), a stereo_pairs target in
     CMakeLists.txt (the default smoke test off)

usage: inference-scheduler/.venv/bin/python demo/stereo_depth/scripts/generate_project.py
           [--config stereo_depth_config.json] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Dict, List

HERE = Path(__file__).resolve().parent
DEMO = HERE.parent
REPO = DEMO.parent.parent
SCHED = REPO / "inference-scheduler"
DEFAULT_OUT = DEMO / "build" / "project"
MODEL = DEMO / "build" / "lightstereo_s.onnx"

sys.path.insert(0, str(SCHED))
sys.path.insert(0, str(HERE))
from src.codegen import CodeGenerator          # noqa: E402
from src.graph import OnnxGraph                # noqa: E402
from src.kernels import KERNEL_REGISTRY        # noqa: E402
from src.stereo import LightStereoFrontend, load_checkpoint, load_formats  # noqa: E402
from stereo_assets import FORMATS, ckpt_path   # noqa: E402

INIT_MACRO = {"VectorOPKernel": "INFERENCE_VECTOROPKERNEL_INSTANCE",
              "MatmulKernel": "INFERENCE_MATMULKERNEL_INSTANCE",
              "ConvKernel": "INFERENCE_CONVKERNEL_INSTANCE",
              "PoolKernel": "INFERENCE_POOLKERNEL_INSTANCE"}
SCHED_ARGS = ["--no-s2d-stem", "--no-fuse-act", "--fc-conv", "off", "--matmul-on-conv", "off"]
GRAPH_KW = dict(fuse_act=False, s2d_stem=False, fc_conv="off", matmul_on_conv="off")


def build_model(height: int, width: int, per_channel=None, path: Path = MODEL):
    """The frontend's ONNX graph at height x width (per-channel weight exponents
    where per-tensor rounding loses more than ``per_channel``; None: off),
    saved to ``path``."""
    import onnx
    if not ckpt_path().exists():
        raise SystemExit(f"{ckpt_path()} missing: run scripts/stereo_assets.py (or run_demo.py)")
    fe = LightStereoFrontend(load_checkpoint(ckpt_path()), load_formats(FORMATS), height, width,
                             per_channel=per_channel)
    m = fe.build()
    path.parent.mkdir(parents=True, exist_ok=True)
    onnx.save(m, str(path))
    return fe


def graph_and_generator(path: Path = MODEL):
    """The demo's graph, as the project generator builds it (postprocess.py
    simulates this one for the bit-exact check)."""
    g = OnnxGraph(str(path), **GRAPH_KW)
    return g, CodeGenerator(graph=g, model_path=str(path))


def populate_drivers(project: Path, driver_dirs: Dict[str, str], active: List[str]) -> List[str]:
    dst = project / "driver"
    dst.mkdir(parents=True, exist_ok=True)
    missing = []
    for k in active:
        src = driver_dirs.get(k)
        src = (DEMO / src).resolve() if src and not Path(src).is_absolute() else (Path(src) if src else None)
        for f in KERNEL_REGISTRY[k].driver_files:
            if src is not None and (src / f).exists():
                shutil.copy2(src / f, dst / f)
            else:
                missing.append(f"{k}/{f}")
    return missing


def emit_glue(project: Path, g, active: List[str]) -> None:
    ins = {t.onnx_name: t for t in g.input_tensors}
    out = g.output_tensors[0]
    defaults = "\n".join(f'#ifndef {INIT_MACRO[k]}\n#  define {INIT_MACRO[k]} "{k}_0"\n#endif' for k in active)
    (project / "test" / "stereo_glue.h").write_text(f"""/*
 * stereo_glue.h — generated by demo/stereo_depth/scripts/generate_project.py:
 * the bridge between stereo_pairs.c and the generated inference API.
 *   in:  left / right {list(ins['left'].shape)} (int16 at 2^-{int(ins['left'].exp)})
 *   out: {out.onnx_name} {list(out.shape)} (float32)
 */
#pragma once

#include "inference.h"

#define BENCH_MODEL_NAME   "lightstereo_s"
#define BENCH_IMAGE_NUMEL  INFERENCE_{ins['left'].c_name.upper()}_SIZE
#define BENCH_DISP_NUMEL   {out.numel}u

{defaults}

static inline int bench_inference_init(void)
{{
    return inference_init({", ".join(INIT_MACRO[k] for k in active)});
}}

static inline void bench_inference_run(inference_buf_t *left, inference_buf_t *right, float *disp)
{{
    inference_run(left, right, disp);
}}
""")


def patch_cmake(project: Path) -> None:
    cm = project / "CMakeLists.txt"
    text = re.sub(r'option\(INFERENCE_BUILD_TEST\s+"[^"]+"\s+ON\)',
                  'option(INFERENCE_BUILD_TEST "Build test_inference smoke test" OFF)', cm.read_text(), count=1)
    macros = " ".join(INIT_MACRO.values())
    cm.write_text(text + f"""
# stereo_pairs — the stereo_depth demo's host (demo/stereo_depth/scripts/generate_project.py)
if(INFERENCE_TARGET STREQUAL "LINUX")
    add_executable(stereo_pairs test/stereo_pairs.c)
    target_link_libraries(stereo_pairs PRIVATE inference m)
    target_include_directories(stereo_pairs PRIVATE test)
    target_compile_options(stereo_pairs PRIVATE -Wall -Wextra -O2)
    if(DEFINED BENCH_DATA_DIR)
        target_compile_definitions(stereo_pairs PRIVATE BENCH_DATA_DIR="${{BENCH_DATA_DIR}}")
    endif()
    foreach(_m IN ITEMS {macros})
        if(DEFINED ${{_m}})
            target_compile_definitions(stereo_pairs PRIVATE ${{_m}}="${{${{_m}}}}")
        endif()
    endforeach()
endif()
""")


def generate(out: Path, driver_dirs: Dict[str, str], height: int, width: int, per_channel=None) -> dict:
    fe = build_model(height, width, per_channel)
    if out.exists():
        shutil.rmtree(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    from inference_scheduler import main as sched_main
    if sched_main(["--out-dir", str(out), *SCHED_ARGS, str(MODEL)]) != 0:
        raise SystemExit("inference-scheduler failed")
    g, cg = graph_and_generator()
    active = [k.name for k in cg._active_kernels]
    missing = populate_drivers(out, driver_dirs, active)
    test = out / "test"
    (test / "test_inference.c").unlink(missing_ok=True)
    shutil.copy2(DEMO / "src" / "stereo_pairs.c", test / "stereo_pairs.c")
    emit_glue(out, g, active)
    patch_cmake(out)
    r = {"project": str(out), "model": str(MODEL), "height": height, "width": width,
         "per_channel": per_channel, "per_channel_convs": len(fe.chexp),
         "active_kernels": active, "missing_drivers": missing, "input_exp": int(fe.exponents["left"])}
    (out / "demo.json").write_text(json.dumps(r, indent=1))      # read by deploy_and_run.py
    return r


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n\n")[0])
    ap.add_argument("--config", default=str(DEMO / "stereo_depth_config.json"))
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT))
    a = ap.parse_args(argv)
    cfg_path = Path(a.config)
    if not cfg_path.exists():
        raise SystemExit(f"{cfg_path} not found: copy stereo_depth_config.json.example and edit it")
    cfg = json.loads(cfg_path.read_text())
    run = cfg.get("run", {})
    r = generate(Path(a.out_dir), cfg.get("local", {}).get("driver_dirs", {}), int(run.get("height", 480)),
                 int(run.get("width", 640)), run.get("per_channel"))
    print(f"project: {r['project']} ({r['width']} x {r['height']}; kernels {', '.join(r['active_kernels'])})")
    if r["missing_drivers"]:
        print(f"warning: missing driver files {r['missing_drivers']} — build the drivers "
              f"(make driver_vectorop_rtl driver_matmul_rtl driver_conv_rtl) or fix local.driver_dirs")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
