#!/usr/bin/env python3
"""generate_project.py — the object_detection demo's KV260 inference project
(doc/plans/YOLO_PLAN.md).

  1. inference-scheduler on assets/models/yolov5n_raw.onnx (yolo_study.py
     fetch: YOLOv5n cut at its three Detect convs, float32) with the image
     demos' graph options (activations fused into their VectorOP call, the
     stride-2 stem as SpaceToDepth + a 4 x 4 conv) -> build/project
  2. the kernels' driver sources (config local.driver_dirs) -> driver/
  3. src/detect_images.c -> test/, its glue test/detect_glue.h (buffer sizes,
     inference_init / inference_run shims), a detect_images target in
     CMakeLists.txt (the default smoke test off)

usage: inference-scheduler/.venv/bin/python demo/object_detection/scripts/generate_project.py
           [--config object_detection_config.json] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Dict, List

DEMO_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = DEMO_DIR.parent.parent
SCHED_DIR = REPO_ROOT / "inference-scheduler"
MODEL = DEMO_DIR / "assets" / "models" / "yolov5n_raw.onnx"
DEFAULT_OUT = DEMO_DIR / "build" / "project"

sys.path.insert(0, str(SCHED_DIR))
from src.codegen import CodeGenerator   # noqa: E402
from src.graph import OnnxGraph         # noqa: E402
from src.kernels import KERNEL_REGISTRY  # noqa: E402

INIT_MACRO = {"VectorOPKernel": "INFERENCE_VECTOROPKERNEL_INSTANCE",
              "MatmulKernel": "INFERENCE_MATMULKERNEL_INSTANCE",
              "ConvKernel": "INFERENCE_CONVKERNEL_INSTANCE",
              "PoolKernel": "INFERENCE_POOLKERNEL_INSTANCE"}


def graph_and_generator():
    """The demo's graph, as the project generator builds it (yolo_study.py and
    the bit-exact check simulate this one)."""
    g = OnnxGraph(str(MODEL), fuse_act=True, s2d_stem=True)
    return g, CodeGenerator(graph=g, model_path=str(MODEL))


def populate_drivers(project: Path, driver_dirs: Dict[str, str], active: List[str]) -> List[str]:
    dst = project / "driver"
    dst.mkdir(parents=True, exist_ok=True)
    missing = []
    for k in active:
        files = KERNEL_REGISTRY[k].driver_files
        src = driver_dirs.get(k)
        src = (DEMO_DIR / src).resolve() if src and not Path(src).is_absolute() else (Path(src) if src else None)
        for f in files:
            if src is not None and (src / f).exists():
                shutil.copy2(src / f, dst / f)
            else:
                missing.append(f"{k}/{f}")
    return missing


def emit_glue(project: Path, g, active: List[str]) -> None:
    (inp,), outs = g.input_tensors, g.output_tensors
    sizes = ", ".join(f"INFERENCE_{t.c_name.upper()}_SIZE" for t in outs)
    defaults = "\n".join(f'#ifndef {INIT_MACRO[k]}\n#  define {INIT_MACRO[k]} "{k}_0"\n#endif' for k in active)
    shapes = "\n".join(f" *   out {i}: {t.onnx_name} {list(t.shape)}" for i, t in enumerate(outs))
    (project / "test" / "detect_glue.h").write_text(f"""/*
 * detect_glue.h — generated by demo/object_detection/scripts/generate_project.py:
 * the bridge between detect_images.c and the generated inference API.
 *   in:    {inp.onnx_name} {list(inp.shape)}
{shapes}
 */
#pragma once

#include "inference.h"

#define BENCH_MODEL_NAME     "yolov5n"
#define BENCH_INPUT_NUMEL    INFERENCE_{inp.c_name.upper()}_SIZE
#define BENCH_NUM_OUTPUTS    {len(outs)}u
#define BENCH_OUTPUT_NUMELS  {{ {sizes} }}

{defaults}

static inline int bench_inference_init(void)
{{
    return inference_init({", ".join(INIT_MACRO[k] for k in active)});
}}

static inline void bench_inference_run(inference_buf_t *in, inference_buf_t *const *out)
{{
    inference_run(in, {", ".join(f"out[{i}]" for i in range(len(outs)))});
}}
""")


def patch_cmake(project: Path) -> None:
    cm = project / "CMakeLists.txt"
    text = re.sub(r'option\(INFERENCE_BUILD_TEST\s+"[^"]+"\s+ON\)',
                  'option(INFERENCE_BUILD_TEST "Build test_inference smoke test" OFF)', cm.read_text(), count=1)
    macros = " ".join(INIT_MACRO.values())
    cm.write_text(text + f"""
# detect_images — the object_detection demo's host (demo/object_detection/scripts/generate_project.py)
if(INFERENCE_TARGET STREQUAL "LINUX")
    add_executable(detect_images test/detect_images.c)
    target_link_libraries(detect_images PRIVATE inference m)
    target_include_directories(detect_images PRIVATE test)
    target_compile_options(detect_images PRIVATE -Wall -Wextra -O2)
    if(DEFINED BENCH_DATA_DIR)
        target_compile_definitions(detect_images PRIVATE BENCH_DATA_DIR="${{BENCH_DATA_DIR}}")
    endif()
    foreach(_m IN ITEMS {macros})
        if(DEFINED ${{_m}})
            target_compile_definitions(detect_images PRIVATE ${{_m}}="${{${{_m}}}}")
        endif()
    endforeach()
endif()
""")


def generate(out: Path, driver_dirs: Dict[str, str]) -> dict:
    if not MODEL.exists():
        raise SystemExit(f"{MODEL} missing: run scripts/yolo_study.py fetch (or run_demo.py)")
    if out.exists():
        shutil.rmtree(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    from inference_scheduler import main as sched_main
    if sched_main(["--out-dir", str(out), str(MODEL)]) != 0:
        raise SystemExit("inference-scheduler failed")
    g, cg = graph_and_generator()
    active = [k.name for k in cg._active_kernels]
    missing = populate_drivers(out, driver_dirs, active)
    test = out / "test"
    (test / "test_inference.c").unlink(missing_ok=True)
    shutil.copy2(DEMO_DIR / "src" / "detect_images.c", test / "detect_images.c")
    emit_glue(out, g, active)
    patch_cmake(out)
    r = {"project": str(out), "model": str(MODEL), "active_kernels": active, "missing_drivers": missing,
         "outputs": [t.onnx_name for t in g.output_tensors]}
    (out / "demo.json").write_text(json.dumps(r, indent=1))      # read by deploy_and_run.py
    return r


def load_config(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f"{path} not found: copy object_detection_config.json.example and edit it")
    return json.loads(path.read_text())


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n\n")[0])
    ap.add_argument("--config", default=str(DEMO_DIR / "object_detection_config.json"))
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT))
    a = ap.parse_args(argv)
    cfg = load_config(Path(a.config))
    r = generate(Path(a.out_dir), cfg.get("local", {}).get("driver_dirs", {}))
    print(f"project: {r['project']} (kernels {', '.join(r['active_kernels'])})")
    if r["missing_drivers"]:
        print(f"warning: missing driver files {r['missing_drivers']} — build the drivers "
              f"(make driver_vectorop_rtl driver_conv_rtl driver_pool_rtl) or fix local.driver_dirs")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
