#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# gen_driver.py — writes the C driver of the RTL MatmulKernel and checks its
# register table against the RTL.
#
# The driver has the API of the one Vitis HLS generates for the HLS
# MatmulKernel (xmatmulkernel.h: XMatmulkernel_Initialize / _Start / _IsDone /
# _Set_<arg> / _Get_<arg> / interrupt calls; Linux UIO and bare-metal
# back ends), so generated inference projects, the benchmarks and the
# calibration runner build against either IP unchanged.  REGS below is the
# register table; the RTL control block rtl/mm_ctrl_s_axi.sv must agree with
# it (--check), and so must the HLS export's xmatmulkernel_hw.h while the HLS
# kernel is still built (--hls-driver).
#
#   gen_driver.py --out DIR            write DIR/MatmulKernel_v1_0/{src,data}/
#   gen_driver.py --check [--hls-driver DIR] [--json]
#                                      compare REGS with the RTL (and the HLS
#                                      driver); exit 1 on a mismatch (with
#                                      --json: print {registers, errors}, exit 0)
# ---------------------------------------------------------------------------
import argparse
import json
import os
import re
import sys

KERNEL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RTL_CTRL = os.path.join(KERNEL_DIR, "rtl", "mm_ctrl_s_axi.sv")

NAME = "MatmulKernel"
PREFIX = "XMatmulkernel"          # C type / function prefix (HLS spelling)
FILE = "xmatmulkernel"            # file stem
MACRO = "XMATMULKERNEL"
# The script named in the generated files (kernels/vectorop_rtl/scripts/gen_driver.py
# reuses this generator with its own kernel name and register table).
GENERATOR = "kernels/matmul_rtl/scripts/gen_driver.py"

# Control registers: name, offset, RTL localparam in mm_ctrl_s_axi.sv.
CTRL = [("AP_CTRL", 0x00, "A_CTRL"), ("GIE", 0x04, "A_GIE"),
        ("IER", 0x08, "A_IER"), ("ISR", 0x0C, "A_ISR")]

# Arguments in register order: name, offset, bits, RTL localparams (lo[, hi]).
REGS = [
    ("a",              0x10, 64, ("A_A0", "A_A1")),
    ("b",              0x1C, 64, ("A_B0", "A_B1")),
    ("c",              0x28, 64, ("A_C0", "A_C1")),
    ("n",              0x34, 32, ("A_N",)),
    ("k",              0x3C, 32, ("A_K",)),
    ("m",              0x44, 32, ("A_M",)),
    ("batch",          0x4C, 32, ("A_BATCH",)),
    ("a_batch_stride", 0x54, 32, ("A_AS",)),
    ("b_batch_stride", 0x5C, 32, ("A_BS",)),
    ("c_batch_stride", 0x64, 32, ("A_CS",)),
    ("b_packed",       0x6C, 32, ("A_BP",)),
    ("gemv_kw",        0x74, 32, ("A_KW",)),
    ("a_to_b",         0x7C, 64, ("A_AB0", "A_AB1")),
]

HEADER = """\
// ---------------------------------------------------------------------------
// {file} — {what}
// Generated by {gen}; do not edit.
// ---------------------------------------------------------------------------
"""


def c_type(bits):
    return "u64" if bits == 64 else "u32"


# ─────────────────────────────────────────────────────────────────────────────
# the driver files
# ─────────────────────────────────────────────────────────────────────────────

def hw_h():
    out = [HEADER.format(gen=GENERATOR, file=f"{FILE}_hw.h", what=f"{NAME} AXI-Lite register offsets (s_axi_ctrl)."),
           "// 0x00 : ap_ctrl  b0 ap_start, b1 ap_done (COR), b2 ap_idle, b3 ap_ready (COR),",
           "//                 b7 auto_restart, b9 interrupt",
           "// 0x04 : GIE      b0 global interrupt enable",
           "// 0x08 : IER      b0 ap_done, b1 ap_ready",
           "// 0x0c : ISR      b0 ap_done, b1 ap_ready (toggle on write)",
           "// 64-bit arguments take two words, low word first.",
           ""]
    for name, off, _ in CTRL:
        out.append(f"#define {MACRO}_CTRL_ADDR_{name:<22}0x{off:02x}")
    for name, off, bits, _ in REGS:
        tag = name.upper() + "_DATA"
        out.append(f"#define {MACRO}_CTRL_ADDR_{tag:<22}0x{off:02x}")
        out.append(f"#define {MACRO}_CTRL_BITS_{tag:<22}{bits}")
    return "\n".join(out) + "\n"


def driver_h():
    protos = []
    for name, _, bits, _ in REGS:
        t = c_type(bits)
        protos.append(f"void {PREFIX}_Set_{name}({PREFIX} *InstancePtr, {t} Data);")
        protos.append(f"{t} {PREFIX}_Get_{name}({PREFIX} *InstancePtr);")
    return HEADER.format(gen=GENERATOR, file=f"{FILE}.h", what=f"driver API of the {NAME} IP.") + f"""\
#ifndef {MACRO}_H
#define {MACRO}_H

#ifdef __cplusplus
extern "C" {{
#endif

#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "{FILE}_hw.h"

#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
#else
typedef struct {{
#ifdef SDT
    char *Name;
#else
    u16 DeviceId;
#endif
    u64 Ctrl_BaseAddress;
}} {PREFIX}_Config;
#endif

typedef struct {{
    u64 Ctrl_BaseAddress;
    u32 IsReady;
}} {PREFIX};

typedef u32 word_type;

#ifndef __linux__
#define {PREFIX}_WriteReg(BaseAddress, RegOffset, Data) \\
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define {PREFIX}_ReadReg(BaseAddress, RegOffset) \\
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define {PREFIX}_WriteReg(BaseAddress, RegOffset, Data) \\
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define {PREFIX}_ReadReg(BaseAddress, RegOffset) \\
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

#ifndef __linux__
#ifdef SDT
int {PREFIX}_Initialize({PREFIX} *InstancePtr, UINTPTR BaseAddress);
{PREFIX}_Config* {PREFIX}_LookupConfig(UINTPTR BaseAddress);
#else
int {PREFIX}_Initialize({PREFIX} *InstancePtr, u16 DeviceId);
{PREFIX}_Config* {PREFIX}_LookupConfig(u16 DeviceId);
#endif
int {PREFIX}_CfgInitialize({PREFIX} *InstancePtr, {PREFIX}_Config *ConfigPtr);
#else
int {PREFIX}_Initialize({PREFIX} *InstancePtr, const char* InstanceName);
int {PREFIX}_Release({PREFIX} *InstancePtr);
#endif

void {PREFIX}_Start({PREFIX} *InstancePtr);
u32 {PREFIX}_IsDone({PREFIX} *InstancePtr);
u32 {PREFIX}_IsIdle({PREFIX} *InstancePtr);
u32 {PREFIX}_IsReady({PREFIX} *InstancePtr);
void {PREFIX}_EnableAutoRestart({PREFIX} *InstancePtr);
void {PREFIX}_DisableAutoRestart({PREFIX} *InstancePtr);

""" + "\n".join(protos) + f"""

void {PREFIX}_InterruptGlobalEnable({PREFIX} *InstancePtr);
void {PREFIX}_InterruptGlobalDisable({PREFIX} *InstancePtr);
void {PREFIX}_InterruptEnable({PREFIX} *InstancePtr, u32 Mask);
void {PREFIX}_InterruptDisable({PREFIX} *InstancePtr, u32 Mask);
void {PREFIX}_InterruptClear({PREFIX} *InstancePtr, u32 Mask);
u32 {PREFIX}_InterruptGetEnabled({PREFIX} *InstancePtr);
u32 {PREFIX}_InterruptGetStatus({PREFIX} *InstancePtr);

#ifdef __cplusplus
}}
#endif

#endif
"""


def driver_c():
    P, B = PREFIX, "InstancePtr->Ctrl_BaseAddress"
    chk_v = ("    Xil_AssertVoid(InstancePtr != NULL);\n"
             "    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);\n")
    chk_n = chk_v.replace("AssertVoid", "AssertNonvoid")

    def ctrl_bit(fn, bit):
        return (f"u32 {P}_{fn}({P} *InstancePtr) {{\n{chk_n}"
                f"    return ({P}_ReadReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL) >> {bit}) & 0x1;\n}}\n")

    s = [HEADER.format(gen=GENERATOR, file=f"{FILE}.c", what=f"register access of the {NAME} IP."),
         f'#include "{FILE}.h"\n',
         "#ifndef __linux__",
         f"int {P}_CfgInitialize({P} *InstancePtr, {P}_Config *ConfigPtr) {{",
         "    Xil_AssertNonvoid(InstancePtr != NULL);",
         "    Xil_AssertNonvoid(ConfigPtr != NULL);",
         "    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;",
         "    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;",
         "    return XST_SUCCESS;",
         "}",
         "#endif\n",
         # ap_start; keep auto_restart (b7) as it is
         f"void {P}_Start({P} *InstancePtr) {{\n{chk_v}"
         f"    u32 Data = {P}_ReadReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL) & 0x80;\n"
         f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL, Data | 0x01);\n}}\n",
         ctrl_bit("IsDone", 1),
         ctrl_bit("IsIdle", 2),
         # ready for the next start once ap_start has been taken
         f"u32 {P}_IsReady({P} *InstancePtr) {{\n{chk_n}"
         f"    return !({P}_ReadReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL) & 0x1);\n}}\n",
         f"void {P}_EnableAutoRestart({P} *InstancePtr) {{\n{chk_v}"
         f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL, 0x80);\n}}\n",
         f"void {P}_DisableAutoRestart({P} *InstancePtr) {{\n{chk_v}"
         f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_AP_CTRL, 0);\n}}\n"]
    for name, _, bits, _ in REGS:
        a = f"{MACRO}_CTRL_ADDR_{name.upper()}_DATA"
        if bits == 64:
            s.append(f"void {P}_Set_{name}({P} *InstancePtr, u64 Data) {{\n{chk_v}"
                     f"    {P}_WriteReg({B}, {a}, (u32)(Data));\n"
                     f"    {P}_WriteReg({B}, {a} + 4, (u32)(Data >> 32));\n}}\n")
            s.append(f"u64 {P}_Get_{name}({P} *InstancePtr) {{\n{chk_n}"
                     f"    u64 Data = {P}_ReadReg({B}, {a});\n"
                     f"    Data += (u64){P}_ReadReg({B}, {a} + 4) << 32;\n"
                     f"    return Data;\n}}\n")
        else:
            s.append(f"void {P}_Set_{name}({P} *InstancePtr, u32 Data) {{\n{chk_v}"
                     f"    {P}_WriteReg({B}, {a}, Data);\n}}\n")
            s.append(f"u32 {P}_Get_{name}({P} *InstancePtr) {{\n{chk_n}"
                     f"    return {P}_ReadReg({B}, {a});\n}}\n")
    s += [f"void {P}_InterruptGlobalEnable({P} *InstancePtr) {{\n{chk_v}"
          f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_GIE, 1);\n}}\n",
          f"void {P}_InterruptGlobalDisable({P} *InstancePtr) {{\n{chk_v}"
          f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_GIE, 0);\n}}\n",
          f"void {P}_InterruptEnable({P} *InstancePtr, u32 Mask) {{\n{chk_v}"
          f"    u32 Register = {P}_ReadReg({B}, {MACRO}_CTRL_ADDR_IER);\n"
          f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_IER, Register | Mask);\n}}\n",
          f"void {P}_InterruptDisable({P} *InstancePtr, u32 Mask) {{\n{chk_v}"
          f"    u32 Register = {P}_ReadReg({B}, {MACRO}_CTRL_ADDR_IER);\n"
          f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_IER, Register & (~Mask));\n}}\n",
          # ISR bits toggle on write: writing a set bit clears it
          f"void {P}_InterruptClear({P} *InstancePtr, u32 Mask) {{\n{chk_v}"
          f"    {P}_WriteReg({B}, {MACRO}_CTRL_ADDR_ISR, Mask);\n}}\n",
          f"u32 {P}_InterruptGetEnabled({P} *InstancePtr) {{\n{chk_n}"
          f"    return {P}_ReadReg({B}, {MACRO}_CTRL_ADDR_IER);\n}}\n",
          f"u32 {P}_InterruptGetStatus({P} *InstancePtr) {{\n{chk_n}"
          f"    return {P}_ReadReg({B}, {MACRO}_CTRL_ADDR_ISR);\n}}"]
    return "\n".join(s) + "\n"


def linux_c():
    P = PREFIX
    return HEADER.format(gen=GENERATOR, file=f"{FILE}_linux.c",
                         what=f"Linux back end of the {NAME} driver: finds the UIO device by name\n"
                              "// and maps its first region (the s_axi_ctrl block).") + f"""\
#ifdef __linux__

#include "{FILE}.h"

#define MAX_UIO_PATH_SIZE 256
#define MAX_UIO_NAME_SIZE 64

static struct {{
    int uio_fd;
    u32 map_size;
}} uio_info;

// First line of a sysfs file, without the newline; 0 on success.
static int line_from_file(const char *path, char *buf, size_t size) {{
    FILE *fp = fopen(path, "r");
    if (!fp) return -1;
    char *s = fgets(buf, (int)size, fp);
    fclose(fp);
    if (!s) return -2;
    buf[strcspn(buf, "\\n")] = 0;
    return 0;
}}

int {P}_Initialize({P} *InstancePtr, const char* InstanceName) {{
    struct dirent **namelist;
    char path[MAX_UIO_PATH_SIZE], name[MAX_UIO_NAME_SIZE];
    int uio_num = -1;

    assert(InstancePtr != NULL);

    int n = scandir("/sys/class/uio", &namelist, 0, alphasort);
    if (n < 0) return XST_DEVICE_NOT_FOUND;
    for (int i = 0; i < n; i++) {{
        if (uio_num < 0 && strncmp(namelist[i]->d_name, "uio", 3) == 0) {{
            int num = atoi(namelist[i]->d_name + 3);
            snprintf(path, sizeof path, "/sys/class/uio/uio%d/name", num);
            if (line_from_file(path, name, sizeof name) == 0 && strcmp(name, InstanceName) == 0)
                uio_num = num;
        }}
        free(namelist[i]);
    }}
    free(namelist);
    if (uio_num < 0) return XST_DEVICE_NOT_FOUND;

    // the s_axi_ctrl block is the device's map0
    unsigned long size = 0;
    snprintf(path, sizeof path, "/sys/class/uio/uio%d/maps/map0/size", uio_num);
    FILE *fp = fopen(path, "r");
    if (!fp) return XST_DEVICE_NOT_FOUND;
    int ok = fscanf(fp, "0x%lx", &size);
    fclose(fp);
    if (ok != 1 || size == 0) return XST_DEVICE_NOT_FOUND;
    uio_info.map_size = (u32)size;

    snprintf(path, sizeof path, "/dev/uio%d", uio_num);
    if ((uio_info.uio_fd = open(path, O_RDWR)) < 0) return XST_OPEN_DEVICE_FAILED;

    void *base = mmap(NULL, uio_info.map_size, PROT_READ | PROT_WRITE, MAP_SHARED, uio_info.uio_fd, 0);
    if (base == MAP_FAILED) {{
        close(uio_info.uio_fd);
        return XST_OPEN_DEVICE_FAILED;
    }}
    InstancePtr->Ctrl_BaseAddress = (u64)(uintptr_t)base;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;
    return XST_SUCCESS;
}}

int {P}_Release({P} *InstancePtr) {{
    assert(InstancePtr != NULL);
    assert(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    munmap((void*)(uintptr_t)InstancePtr->Ctrl_BaseAddress, uio_info.map_size);
    close(uio_info.uio_fd);
    InstancePtr->IsReady = 0;
    return XST_SUCCESS;
}}

#endif
"""


def sinit_c():
    P = PREFIX
    return HEADER.format(gen=GENERATOR, file=f"{FILE}_sinit.c",
                         what=f"bare-metal back end of the {NAME} driver: looks the instance up\n"
                              f"// in {P}_ConfigTable (generated by the BSP into {FILE}_g.c).") + f"""\
#ifndef __linux__

#include "xstatus.h"
#ifdef SDT
#include "xparameters.h"
#endif
#include "{FILE}.h"

extern {P}_Config {P}_ConfigTable[];

#ifdef SDT
{P}_Config *{P}_LookupConfig(UINTPTR BaseAddress) {{
    for (int Index = 0; {P}_ConfigTable[Index].Name != NULL; Index++) {{
        if (!BaseAddress || {P}_ConfigTable[Index].Ctrl_BaseAddress == BaseAddress)
            return &{P}_ConfigTable[Index];
    }}
    return NULL;
}}

int {P}_Initialize({P} *InstancePtr, UINTPTR BaseAddress) {{
    Xil_AssertNonvoid(InstancePtr != NULL);
    {P}_Config *ConfigPtr = {P}_LookupConfig(BaseAddress);
    if (ConfigPtr == NULL) {{
        InstancePtr->IsReady = 0;
        return XST_DEVICE_NOT_FOUND;
    }}
    return {P}_CfgInitialize(InstancePtr, ConfigPtr);
}}
#else
{P}_Config *{P}_LookupConfig(u16 DeviceId) {{
    for (int Index = 0; Index < XPAR_{MACRO}_NUM_INSTANCES; Index++) {{
        if ({P}_ConfigTable[Index].DeviceId == DeviceId)
            return &{P}_ConfigTable[Index];
    }}
    return NULL;
}}

int {P}_Initialize({P} *InstancePtr, u16 DeviceId) {{
    Xil_AssertNonvoid(InstancePtr != NULL);
    {P}_Config *ConfigPtr = {P}_LookupConfig(DeviceId);
    if (ConfigPtr == NULL) {{
        InstancePtr->IsReady = 0;
        return XST_DEVICE_NOT_FOUND;
    }}
    return {P}_CfgInitialize(InstancePtr, ConfigPtr);
}}
#endif

#endif
"""


# BSP metadata: the classic flow reads the .mdd + .tcl, the system-device-tree
# flow the .yaml and src/CMakeLists.txt; the BSP Makefile builds src/ into libxil.
def data_files():
    mdd = f"""\
# {NAME} driver (classic BSP flow); generated by {GENERATOR}
OPTION psf_version = 2.1;

BEGIN driver {NAME}

 OPTION supported_peripherals = ({NAME}_v1_0 );
 OPTION driver_state = ACTIVE;
 OPTION copyfiles = all;
 OPTION name = {NAME};
 OPTION version = 1.0;

END driver
"""
    tcl = f"""\
# {NAME} driver (classic BSP flow): xparameters.h entries and the config
# table {FILE}_g.c; generated by {GENERATOR}
proc generate {{drv_handle}} {{
    xdefine_include_file $drv_handle "xparameters.h" "{PREFIX}" \\
        "NUM_INSTANCES" \\
        "DEVICE_ID" \\
        "C_S_AXI_CTRL_BASEADDR" \\
        "C_S_AXI_CTRL_HIGHADDR"

    xdefine_config_file $drv_handle "{FILE}_g.c" "{PREFIX}" \\
        "DEVICE_ID" \\
        "C_S_AXI_CTRL_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "{PREFIX}" \\
        "DEVICE_ID" \\
        "C_S_AXI_CTRL_BASEADDR" \\
        "C_S_AXI_CTRL_HIGHADDR"
}}
"""
    yaml = f"""\
%YAML 1.2
---
# {NAME} driver (system-device-tree flow); generated by {GENERATOR}
title: {NAME} driver
type: driver
properties:
    compatible:
        items:
            - const: xlnx,{NAME}-1.0
config:
    - {PREFIX}_Config
required:
    - compatible
    - reg
additionalProperties:
   - interrupts
   - interrupt-parent
"""
    cmake = f"""\
# {NAME} driver library (system-device-tree BSP flow);
# generated by {GENERATOR}
cmake_minimum_required(VERSION 3.15)
project({NAME})
find_package(common)
collector_create (PROJECT_LIB_SOURCES "${{CMAKE_CURRENT_SOURCE_DIR}}")
collect (PROJECT_LIB_SOURCES {FILE}.c)
collect (PROJECT_LIB_SOURCES {FILE}_sinit.c)
collect (PROJECT_LIB_SOURCES {FILE}_linux.c)
collect (PROJECT_LIB_SOURCES {FILE}_g.c)
collector_list (_sources PROJECT_LIB_SOURCES)
collector_create (PROJECT_LIB_HEADERS "${{CMAKE_CURRENT_SOURCE_DIR}}")
collect (PROJECT_LIB_HEADERS {FILE}.h)
collect (PROJECT_LIB_HEADERS {FILE}_hw.h)
collector_list (_headers PROJECT_LIB_HEADERS)
file(COPY ${{_headers}} DESTINATION ${{CMAKE_BINARY_DIR}}/include)
include_directories(${{CMAKE_BINARY_DIR}}/include)
add_library({NAME} STATIC ${{_sources}})
set_target_properties({NAME} PROPERTIES LINKER_LANGUAGE C)
"""
    make = f"""\
# {NAME} driver library (classic BSP flow: the BSP passes COMPILER, ARCHIVER
# and the flags); generated by {GENERATOR}
COMPILER=
ARCHIVER=
CP=cp
RM=rm
COMPILER_FLAGS=
EXTRA_COMPILER_FLAGS=
ARCHIVER_FLAGS=

CORENAME={NAME}

RELEASEDIR=../../../lib
OBJDIR=$(RELEASEDIR)
LIBDIR=$(RELEASEDIR)
INCLUDEDIR=../../../include
INCLUDES=-I./. -I$(INCLUDEDIR)

SRCS := $(wildcard *.c)
HEADERS := $(wildcard *.h)

LIB := $(LIBDIR)/libxil.a
OBJS := $(addprefix $(OBJDIR)/,$(addsuffix .o,$(basename $(SRCS))))
RELEASE_HEADERS := $(addprefix $(INCLUDEDIR)/,$(notdir $(HEADERS)))

$(OBJDIR)/%.o: %.c
\t$(COMPILER) $(COMPILER_FLAGS) $(EXTRA_COMPILER_FLAGS) $(INCLUDES) -o $@ $<
$(LIB): $(OBJS)
\t$(ARCHIVER) $(ARCHIVER_FLAGS) -r $@ $^

$(INCLUDEDIR)/%.h: %.h
\t$(CP) $< $@

$(OBJS): $(SRCS) | $(HEADERS)

include: $(RELEASE_HEADERS)
includes: include
libs: $(LIB) banner
objs: $(OBJS)

clean:
\t$(RM) -f $(LIB) $(OBJS) $(RELEASE_HEADERS)
banner:
\techo "Building $(CORENAME)"

.PHONY: clean include objs libs includes banner
"""
    return {f"data/{NAME}.mdd": mdd, f"data/{NAME}.tcl": tcl, f"data/{NAME}.yaml": yaml,
            "src/CMakeLists.txt": cmake, "src/Makefile": make}


def files():
    f = {f"src/{FILE}_hw.h": hw_h(), f"src/{FILE}.h": driver_h(), f"src/{FILE}.c": driver_c(),
         f"src/{FILE}_linux.c": linux_c(), f"src/{FILE}_sinit.c": sinit_c()}
    f.update(data_files())
    return f


def write(out_dir):
    root = os.path.join(out_dir, f"{NAME}_v1_0")
    for rel, text in files().items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # keep the timestamp of an unchanged file (make does not rebuild its users)
        if os.path.exists(path) and open(path).read() == text:
            continue
        with open(path, "w") as fh:
            fh.write(text)
    return root


# ─────────────────────────────────────────────────────────────────────────────
# checks
# ─────────────────────────────────────────────────────────────────────────────

def rtl_localparams(path=RTL_CTRL):
    """{localparam name: value} of the N'hXX address constants in the RTL control block."""
    text = re.sub(r"//[^\n]*", "", open(path).read())
    return {n: int(v, 16) for n, v in re.findall(r"\b(A_\w+)\s*=\s*\d+'h([0-9A-Fa-f]+)", text)}


def check_rtl(path=RTL_CTRL):
    errors = []
    lp = rtl_localparams(path)
    want = {}
    for name, off, rtl in CTRL:
        want[rtl] = (name, off)
    for name, off, bits, rtl in REGS:
        for i, p in enumerate(rtl):
            want[p] = (name + (f" word {i}" if bits == 64 else ""), off + 4 * i)
        if len(rtl) != bits // 32:
            errors.append(f"{name}: {bits} bits but {len(rtl)} RTL address constants")
    for p, (what, off) in want.items():
        if p not in lp:
            errors.append(f"{what}: {p} is not defined in {os.path.relpath(path, KERNEL_DIR)}")
        elif lp[p] != off:
            errors.append(f"{what}: {p} = 0x{lp[p]:02X} in the RTL, 0x{off:02X} in the driver table")
    for p in sorted(set(lp) - set(want)):
        errors.append(f"RTL address constant {p} = 0x{lp[p]:02X} is not in the driver table")
    return errors


def _defines(text):
    return {n: v for n, v in re.findall(r"#define\s+(\w+_CTRL_(?:ADDR|BITS)_\w+)\s+(\w+)", text)}


def _prototypes(text):
    text = re.sub(r"\s+", " ", text)
    return set(re.findall(rf"\b(?:void|u32|u64|int|{PREFIX}_Config\*) {PREFIX}_\w+\([^)]*\);", text))


def check_hls(hls_dir):
    """The HLS export's register offsets and prototypes against the generated driver."""
    src = os.path.join(hls_dir, "src")
    gen = files()
    errors = []
    hls_def = _defines(open(os.path.join(src, f"{FILE}_hw.h")).read())
    our_def = _defines(gen[f"src/{FILE}_hw.h"])
    for n in sorted(set(hls_def) | set(our_def)):
        a, b = hls_def.get(n), our_def.get(n)
        if a is None or b is None or int(a, 0) != int(b, 0):
            errors.append(f"{n}: HLS {a}, generated {b}")
    hls_p = _prototypes(open(os.path.join(src, f"{FILE}.h")).read())
    our_p = _prototypes(gen[f"src/{FILE}.h"])
    for p in sorted(hls_p - our_p):
        errors.append(f"only in the HLS driver: {p}")
    for p in sorted(our_p - hls_p):
        errors.append(f"only in the generated driver: {p}")
    return errors


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0] if __doc__ else None)
    ap.add_argument("--out", help=f"write DIR/{NAME}_v1_0/{{src,data}}/")
    ap.add_argument("--check", action="store_true",
                    help=f"compare the register table with rtl/{os.path.basename(RTL_CTRL)}")
    ap.add_argument("--rtl", metavar="SV", default=RTL_CTRL,
                    help=f"with --check: the RTL control block (default: rtl/{os.path.basename(RTL_CTRL)})")
    ap.add_argument("--hls-driver", metavar="DIR",
                    help=f"with --check: also compare with the HLS export's {NAME}_v1_0 driver")
    ap.add_argument("--json", action="store_true",
                    help="with --check: print {registers, errors} as JSON and exit 0 (the caller judges)")
    a = ap.parse_args(argv)
    if not a.out and not a.check:
        ap.error("nothing to do: give --out and / or --check")
    if a.out:
        root = write(a.out)
        if not a.json:
            print(f"driver -> {root}")
    if a.check:
        errors = check_rtl(a.rtl)
        if a.hls_driver:
            errors += check_hls(a.hls_driver)
        if a.json:
            regs = {n: {"offset": off, "bits": bits} for n, off, bits, _ in REGS}
            print(json.dumps({"registers": regs, "errors": errors}))
            return 0
        else:
            for e in errors:
                print("MISMATCH", e)
            what = "RTL" + (" and HLS driver" if a.hls_driver else "")
            print(f"register table vs {what}: " + (f"{len(errors)} mismatches" if errors else
                                                 f"{len(REGS)} arguments + {len(CTRL)} control registers agree"))
        return 1 if errors else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
