/*
 * inference_prof.h — per-layer wall-clock profiler for generated inference
 *                    projects.
 *
 * Aggregate-only: each layer keeps a count, summed nanoseconds, min, and max.
 * No sample buffers, no percentiles — total RAM cost is 40 bytes per layer
 * (five uint64_t counters) plus a name pointer.  Mean is computed from total/count at dump time.
 *
 * Profiling is opt-in at compile time.  Define INFERENCE_PROFILING=1 (e.g.
 * via cmake -DINFERENCE_PROFILING=ON) to compile begin/end into real
 * clock_gettime() calls; otherwise the macros expand to no-ops and this
 * translation unit may be dropped from the link line entirely.
 *
 * Thread-safety: none.  Designed for the single-threaded inference loop
 * generated by inference-scheduler.  Each layer index has its own
 * start-time slot, so begin/end brackets for DIFFERENT indices may freely
 * overlap (which they do under cross-lane kernel parallelism — Conv ‖ Pool
 * ‖ VectorOP).  For the SAME layer index, a second begin without an
 * intervening end overwrites the first start time.
 *
 * Typical usage from a host benchmark:
 *
 *   inference_prof_init(inference_num_layers(),
 *                       inference_layer_names_ptr());
 *   for (i = 0; i < warmup; ++i) inference_run(...);
 *   inference_prof_reset();        // discard warmup samples
 *   for (; i < n; ++i) inference_run(...);
 *   inference_prof_dump_json(stdout);
 *   inference_prof_deinit();
 */
#pragma once

#include <stdio.h>

#ifndef INFERENCE_PROFILING
#  define INFERENCE_PROFILING 0
#endif

#ifdef __cplusplus
extern "C" {
#endif

#if INFERENCE_PROFILING

/* Allocate per-layer counter storage and remember the names array.
 * The names array is borrowed (not copied); it must outlive the profiler.
 * Returns 0 on success, non-zero on allocation failure. */
int  inference_prof_init(unsigned n_layers, const char *const *names);

/* Zero all counters but keep the layer count and names.  Use this between
 * warmup and the timed measurement window. */
void inference_prof_reset(void);

/* Mark the start / end of one layer's wall-clock window.  Brackets for
 * different layer indices may overlap; per-index begin/end must alternate.
 * layer_idx must be in [0, n_layers). */
void inference_prof_begin(unsigned layer_idx);
void inference_prof_end  (unsigned layer_idx);

/* Emit one self-contained JSON line:
 *   LAYERS_JSON: {"layers":[{"i":N,"name":"...","calls":N,"mean_us":F,
 *                            "min_us":F,"max_us":F,"total_us":F},...]}
 *
 * The "LAYERS_JSON: " prefix is the marker used by host parsers to find
 * this line amongst other stdout output. */
void inference_prof_dump_json(FILE *f);

/* Release the counter storage allocated by inference_prof_init(). */
void inference_prof_deinit(void);

#  define INFERENCE_PROF_BEGIN(i)  inference_prof_begin((i))
#  define INFERENCE_PROF_END(i)    inference_prof_end((i))

#else

#  define INFERENCE_PROF_BEGIN(i)  ((void)0)
#  define INFERENCE_PROF_END(i)    ((void)0)

#endif /* INFERENCE_PROFILING */

#ifdef __cplusplus
}
#endif
