#!/usr/bin/env python3
"""Generates rtl/PoolingKernel.v, the Verilog-2001 IP top level, from the
parameter and port header of rtl/pl_core.sv (same names, widths, defaults).

    python3 scripts/gen_top_wrapper.py [rtl/pl_core.sv] [rtl/PoolingKernel.v]
"""
import re
import sys

src = sys.argv[1] if len(sys.argv) > 1 else 'rtl/pl_core.sv'
dst = sys.argv[2] if len(sys.argv) > 2 else 'rtl/PoolingKernel.v'
text = open(src).read()

hdr = re.search(r'module\s+pl_core\s*(?:import[^;]*;)?\s*#\((.*?)\)\s*\((.*?)\);', text, re.S)
params_txt, ports_txt = hdr.group(1), hdr.group(2)
params = re.findall(r'parameter\s+int\s+(\w+)\s*=\s*([^,\n]+)', params_txt)
ports = []
for line in ports_txt.splitlines():
    line = line.split('//')[0].strip().rstrip(',')
    if not line:
        continue
    m = re.match(r'(input|output)\s+logic\s*(\[[^\]]+\])?\s*(\w+)$', line)
    if not m:
        sys.exit(f'cannot parse port line: {line!r}')
    ports.append((m.group(1), (m.group(2) or '').strip(), m.group(3)))

out = []
out.append('// ---------------------------------------------------------------------------')
out.append('// PoolingKernel — IP top level (Verilog-2001) of the RTL Q8.8 2-D pooling kernel.')
out.append('// GENERATED by scripts/gen_top_wrapper.py from rtl/pl_core.sv; do not edit.')
out.append('// Same module name, parameters and ports as the Vitis-HLS PoolingKernel export.')
out.append('// ---------------------------------------------------------------------------')
out.append('module PoolingKernel #(')
out.append(',\n'.join(f'  parameter {n} = {v.strip()}' for n, v in params))
out.append(') (')
out.append(',\n'.join(f'  {d:6s} wire {w + " " if w else ""}{n}' for d, w, n in ports))
out.append(');')
out.append('')
out.append('  pl_core #(')
out.append(',\n'.join(f'    .{n}({n})' for n, _ in params))
out.append('  ) u_core (')
out.append(',\n'.join(f'    .{n}({n})' for _, _, n in ports))
out.append('  );')
out.append('')
out.append('endmodule')
open(dst, 'w').write('\n'.join(out) + '\n')
print(f'{dst}: {len(params)} parameters, {len(ports)} ports')
